#!/usr/bin/env bash
# gf180-pll :: reference-phase-transfer :: verify tb.json's configuration bits
# against sim/lib/pll_top_dut.sh, the single owner of that encoding.
#
# Same check, same reasoning, as sim/reference-spur/testbench/check_config.sh
# (this campaign reuses that campaign's exact operating point): tb.json's
# static configuration bits cannot be generated by a bash function because a
# JSON manifest is data, so this script asserts they are EXACTLY what
# sim/lib/pll_top_dut.sh produces rather than leaving a reader to trust that
# they look plausible.  Run it whenever the operating point changes.
#
#   ./check_config.sh      # prints each field and a PASS/FAIL verdict
#
# Exit 0 if every bit matches, 1 otherwise.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${HERE}/../../.." && pwd)"
TB="${HERE}/tb.json"

# shellcheck source=/dev/null
. "${ROOT}/sim/lib/pll_top_dut.sh"

# The operating point tb.json declares, read back out of the manifest itself so
# this check cannot drift from it.
N="$(python3 -c 'import json,sys; print(int(float(json.load(open(sys.argv[1]))["params"]["nratio"])))' "${TB}")"
BAND=6
TRIM=0
# The lock detector's 4-bit window trim (DR-014, #411): the CENTRE code.
# This campaign is not about the lock window, so it runs the cell at the
# middle of its range; sim/lock-window-trim owns the per-part code.
WINTRIM=${CLOOP_WINDOW_TRIM_NOMINAL:-8}

fail=0

echo "reference-phase-transfer config check -- N=${N}, band=${BAND}, Icp trim code=${TRIM}"
echo "divider (cloop_divider_params ${N}):"
cloop_check_codes "${TB}" "$(cloop_divider_params "${N}")"
echo "VCO band (cloop_band_params ${BAND}):"
cloop_check_codes "${TB}" "$(cloop_band_params "${BAND}")"
echo "Icp trim (cloop_trim_params ${TRIM}):"
cloop_check_codes "${TB}" "$(cloop_trim_params "${TRIM}")"
echo "window trim (cloop_window_trim_params ${WINTRIM}):"
cloop_check_codes "${TB}" "$(cloop_window_trim_params "${WINTRIM}")"

# The DUT instance line in the fragment must be `cloop_instance`'s output
# verbatim, folded onto continuation lines: same ports, same ORDER, since the
# instance line is positional and a swapped pair simulates happily.
echo "DUT instance line (cloop_instance xdut):"
cloop_check_instance_line "${HERE}/tb_ref_phase_transfer.sp" xdut

if [ "${fail}" -eq 0 ]; then
  echo "PASS -- tb.json's configuration bits are sim/lib/pll_top_dut.sh's own encoding"
else
  echo "FAIL -- fix tb.json (or the deck) to match sim/lib/pll_top_dut.sh" >&2
fi
exit "${fail}"
