#!/usr/bin/env python3
"""gf180-pll :: period-jitter :: in-band-bound -- results/*.json -> results/SUMMARY.md.

Formats; computes nothing that is not a ratio or an extremum of committed
numbers.  Every figure the README, DR-033 and `spec/pll.md` quote is in the
output of this script, so a reader can check a quoted value against the JSON
without re-running ngspice.

    sim/period-jitter/in-band-bound/summarize.py \\
        > sim/period-jitter/in-band-bound/results/SUMMARY.md
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RES = HERE / "results"
sys.path.insert(0, str(HERE))

import ib_extract as ib  # noqa: E402
import run  # noqa: E402


def load(name):
    p = RES / name
    return json.loads(p.read_text()) if p.is_file() else None


def main() -> int:
    points = run.load_points()
    loop = load("loop.json")
    rows, missing = [], []
    for name in points:
        b = load(f"bound_{name}.json")
        d = load(f"digital_{name}.json")
        if not (b and d and load(f"cp_{name}.json") and load(f"cells_{name}.json")
                and load(f"clkload_{name}.json") and load(f"ldload_{name}.json")):
            missing.append(name)
            continue
        rows.append((name, b, d))
    ref = run.REFERENCE_POINT
    val = load(f"validate_{ref}.json")
    out: list[str] = []
    a = out.append
    a("<!-- GENERATED by sim/period-jitter/in-band-bound/summarize.py.")
    a("     Do not edit: regenerate with")
    a("       sim/period-jitter/in-band-bound/summarize.py \\")
    a("           > sim/period-jitter/in-band-bound/results/SUMMARY.md -->")
    a("")
    a("# Random period jitter of the in-band generators, bounded — results")
    a("")
    a("An upper bound on the random (noise-driven) period jitter the **charge "
      "pump, the PFD, the feedback divider and the lock detector** contribute to "
      "the locked output, at every point of the mandated 45-point PVT grid. Those "
      "four are the generators `../random-bound/` (issue #520, DR-032) states as "
      "outside its own scope. The comparison is against the margin DR-032's bound "
      f"leaves inside the {run.BUDGET_PCT:.2f} % RMS `spec/pll.md` allocates to "
      "the random component — not against the whole allocation. The inequalities "
      "are in `ib_extract.py`'s module docstring and the directory README; the "
      "decision record is `spec/decision-records/DR-033-*.md`.")
    a("")
    if rows:
        env = rows[0][1]["environment"]
        a(f"- ngspice: `{env['ngspice']}`")
        a(f"- PDK models: `{env['pdk_models']}`")
        heads = sorted({r[1]["environment"]["repo_head"] for r in rows})
        a(f"- repo HEAD at run time: {', '.join(f'`{h}`' for h in heads)}")
        dirty = [r[0] for r in rows if r[1]["environment"]["repo_dirty"]]
        a("- `design/`, `spec/` or `sim/period-jitter/` modified at run time: "
          f"{'**yes** at ' + ', '.join(dirty) if dirty else 'no, at every point'}")
        utc = sorted(r[1]["environment"]["run_utc"] for r in rows)
        a(f"- runs (UTC): {utc[0]} … {utc[-1]}")
    a(f"- points present: **{len(rows)} of {len(points)}**"
      + (f" — MISSING: {', '.join(missing)}" if missing else ""))
    if missing:
        a("")
        a("**This is a partial grid. No bound is established over the mandated "
          "grid until every point above is present.**")
    a("")

    # ------------------------------------------------------------------ grid
    if rows:
        tot = [r[1]["bound"]["in_band_pct"] for r in rows]
        comb = [r[1]["bound"]["combined_pct"] for r in rows]
        worst = max(rows, key=lambda r: r[1]["bound"]["in_band_pct"])
        worst_h = min(rows, key=lambda r: r[1]["bound"]["headroom"])
        a("## The bound, per point")
        a("")
        a(f"**Worst in-band bound: `{worst[0]}`, {worst[1]['bound']['in_band_pct']:.4f} % "
          f"RMS.** Range over the {len(rows)} points: {min(tot):.4f} … {max(tot):.4f} %. "
          f"**Tightest headroom: `{worst_h[0]}`, {worst_h[1]['bound']['headroom']:.1f}×** the "
          "margin DR-032 leaves at that same point "
          f"({worst_h[1]['bound']['remaining_pct']:.4f} %). Points whose in-band bound "
          f"exceeds that remaining margin: **{sum(r[1]['bound']['headroom'] < 1 for r in rows)}**. "
          f"Points whose combined (VCO-side + in-band) bound exceeds the "
          f"{run.BUDGET_PCT:.2f} % allocation: "
          f"**{sum(not r[1]['bound']['clears'] for r in rows)}**; combined range "
          f"{min(comb):.4f} … {max(comb):.4f} %.")
        a("")
        a("`VCO` is `../random-bound`'s own bound at this point "
          "(`../random-bound/results/transient_<point>.json`), `rem` the margin it "
          f"leaves inside {run.BUDGET_PCT:.2f} % — `sqrt(budget² − VCO²)`, the two "
          "adding in quadrature because their sources are independent. `CP`, `PFD`, "
          "`DIV`, `LD` are the four blocks' own quadrature totals, `in-band` their "
          "quadrature sum, `head` = `rem / in-band`, `comb` = "
          "`sqrt(VCO² + in-band²)`. All in % of the output period, RMS.")
        a("")
        a("| Point | f0 (MHz) | t_on (ns) | duty | CP | PFD | DIV | LD | **in-band** | "
          "VCO | rem | head | comb |")
        a("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for name, b, d in rows:
            bl = b["by_block_pct"]
            bd = b["bound"]
            a(f"| `{name}` | {b['f0_Hz'] / 1e6:.3f} | {d['t_on_s'] * 1e9:.3f} | "
              f"{b['detail']['cp_current']['duty'] * 100:.2f} % | "
              f"{bl['charge_pump']:.5f} | {bl['pfd']:.5f} | {bl['divider_chain']:.5f} | "
              f"{bl['lock_detector']:.6f} | **{bd['in_band_pct']:.5f}** | "
              f"{bd['vco_bound_pct']:.4f} | {bd['remaining_pct']:.4f} | "
              f"{bd['headroom']:.1f}× | {bd['combined_pct']:.4f} |")
        a("")

        # ------------------------------------------------------- per-term
        a("### Every term, at the tightest-headroom point")
        a("")
        b = worst_h[1]
        a(f"`{worst_h[0]}`. `corr` is the same term with its stages summed as "
          "perfectly correlated amplitudes instead of in quadrature — reported so "
          "the size of the independence assumption is visible, not used.")
        a("")
        a("| Term | block | stages | in quadrature (%) | `corr` (%) | note |")
        a("|---|---|---|---|---|---|")
        notes = {
            "cp_current": "output current noise, gated to the conduction window",
            "cp_off_state": "the same, over the rest of the reference period",
            "divider_clk_loading": "gate-only load on `CLK`, no loop, no `4sin²`",
            "lock_detector_loading": "gate-only load on `UP`/`DN`; 0 timing stages",
        }
        for k, v in sorted(b["bound"]["terms_pct"].items(), key=lambda kv: -kv[1]):
            det = b["detail"][k]
            note = notes.get(k, "")
            if det.get("common_mode"):
                note = ("common mode between UP and DN, × imbalance "
                        f"{det['common_mode_scale']:.3g}")
            stages = det.get("n_stages", det.get("n_stages_in_timing_path", "—"))
            corr = (f"{det['pct_if_perfectly_correlated']:.6f}"
                    if "pct_if_perfectly_correlated" in det else "—")
            a(f"| `{k}` | {det.get('block', '')} | {stages} | {v:.6f} | {corr} | "
              f"{note} |")
        a("")
        cm = b["detail"]["_common_mode"]
        a(f"The up/down leg imbalance at this point: measured "
          f"{cm['measured_imbalance'] * 100:.3f} % (`I_up` = {cm['i_up_A'] * 1e6:.4f} µA, "
          f"`I_dn` = {cm['i_dn_A'] * 1e6:.4f} µA); the scale used is "
          f"{cm['scale'] * 100:.1f} %, set by the **{cm['set_by']}**.")
        a("")
        a("Per single stage at this point, each cell's own trip-point noise into "
          f"{1e15 * load(f'cells_{worst_h[0]}.json')['c_load_F']:.0f} fF divided by its "
          "own slowest measured slew:")
        a("")
        a("| Cell | σ_v (mV) | slew (V/ns) | one stage (%) |")
        a("|---|---|---|---|")
        for c, v in sorted(b["detail"]["_per_cell_stage"].items(),
                           key=lambda kv: -kv[1]["pct_one_stage"]):
            a(f"| `{c}` | {v['sigma_v_V'] * 1e3:.4f} | "
              f"{v['slew_V_per_s'] / 1e9:.3f} | {v['pct_one_stage']:.6f} |")
        a("")
        rt = b["detail"]["_retired_all_device_count"]
        a("What the every-inverting-device-in-series count this campaign does NOT "
          f"use would have said instead, charging every block's devices the worst "
          f"cell (`{rt['worst_cell']}`) and putting them all in one path: "
          + ", ".join(f"{k} {v:.4f} %" for k, v in sorted(rt["pct_per_block"].items()))
          + ". The declared timing paths (`ib_extract.TIMING_PATHS`, checked against "
          "the netlist at every point) are what replace it.")
        a("")

        # ------------------------------------------------------- allowance
        al = [r[1]["allowance"]["sigma_t_at_pfd_input_s"] for r in rows]
        a("### How much room is left, in picoseconds at the PFD's input")
        a("")
        a("The independent-per-cycle timing jitter at the PFD's input that would, "
          "on its own, consume the whole margin DR-032 leaves — the honest way to "
          "say how far the four blocks are from mattering. Over the grid: "
          f"**{min(al) * 1e12:.1f} … {max(al) * 1e12:.1f} ps**, against reference and "
          "feedback edges whose own measured slews put every stage's contribution "
          "in the femtosecond decade.")
        a("")

    # ------------------------------------------------------------ loop
    if loop:
        a("## The loop (stage `loop`)")
        a("")
        a(f"{loop['n_loops']} loops `T = A Z(s)/s` over the as-built filter's "
          f"R ∈ {loop['filter_R_ohm'][0] / 1e3:.1f}…{loop['filter_R_ohm'][1] / 1e3:.1f} kΩ, "
          f"C1 ∈ {loop['filter_C1_F'][0] * 1e12:.1f}…{loop['filter_C1_F'][1] * 1e12:.1f} pF, "
          f"C2 ∈ {loop['filter_C2_F'][0] * 1e12:.2f}…{loop['filter_C2_F'][1] * 1e12:.2f} pF, "
          f"every gain with PM ≥ {loop['pm_floor_deg']:g}° (crossovers "
          f"{loop['fc_range_Hz'][0] / 1e3:.1f} kHz … {loop['fc_range_Hz'][1] / 1e6:.3f} MHz) "
          f"— read from `{loop['source']}` so both directories envelope the same "
          "loop set.")
        a("")
        a("- peak of the **input-to-output** envelope `max |T/(1+T)|²`: "
          f"**{loop['closed_loop_peak_sq']:.3f}**. (`../random-bound` envelopes "
          "`|1/(1+T)|²`, the complementary transfer: the same loop that suppresses "
          "the VCO's own noise passes an input-referred source, which is why these "
          "four blocks need their own calculation and not a reuse of that bound's.)")
        a("- peak of the **product** `|T/(1+T)|² · 4 sin²(π f T₀)` — the whole "
          "reason these four blocks are small: "
          f"**{loop['product_peak']:.3e}** at "
          f"{loop['product_peak_at_Hz'] / 1e6:.3f} MHz "
          f"(at f₀ = {loop['product_peak_f0_Hz'] / 1e6:g} MHz; each point's bound "
          "uses its own measured f₀ and integrates the exact weight, never this "
          "single number)")
        a("")

    # ------------------------------------------------------- gate loads
    if rows:
        a("## The two gate-only loads")
        a("")
        a("Neither the divider chain's clock input nor the lock detector's XOR "
          "input has a channel connected to the node it loads — both couple back "
          "through `C_gd` alone. That makes the noise they put on the node rise as "
          "`f²` up to the capacitive-divider ceiling, so the variance is **not "
          "monotone** in the drive resistance and a single \"conservative\" value "
          "would not have been one. Each is therefore characterized over a "
          "four-value drive-resistance sweep and the **maximum** is used.")
        a("")
        a("| Point | load | σ_v (µV) by R_drive (Ω) | used | peak density at | "
          "last decade's share of the variance |")
        a("|---|---|---|---|---|---|")
        for name, b, d in rows:
            for stage, label in (("clkload", "CLK (divider)"),
                                 ("ldload", "UP (lock detector)")):
                g = load(f"{stage}_{name}.json")
                if not g:
                    continue
                sweep = " / ".join(
                    f"{g['sigma_v_by_r_drive_V'][k] * 1e6:.2f}"
                    for k in sorted(g["sigma_v_by_r_drive_V"], key=float))
                dc = g["decade_cumulative_V2"]
                share = (1.0 - dc[-2]["var_V2"] / dc[-1]["var_V2"]) if len(dc) > 1 else 1.0
                a(f"| `{name}` | {label} | {sweep} | "
                  f"{g['r_drive_ohm']:.0f} Ω | "
                  f"{g['peak_density_at_Hz']:.3g} Hz | {share * 100:.1f} % |")
        a("")
        a("The sweep order is "
          + " / ".join(f"{r:.0f}" for r in run.R_DRIVE_SWEEP_OHM)
          + " Ω, the grid top "
          f"{run.CLKLOAD_F_HI:.0g} Hz — four decades above these devices' own "
          "transit frequency. The last column is why no tail is extrapolated past "
          "it: the density there is flat, not falling as `f^-2`, so there is no "
          "measured roll-off to extrapolate and the integration stops at a stated "
          "band instead. Both terms are five orders below the allocation, so the "
          "choice cannot change the verdict.")
        a("")

    # ------------------------------------------------------------ validation
    if val:
        a(f"## Does the measurement depend on what it should not? (stage "
          f"`validate`, `{ref}`)")
        a("")
        ts = val["timestep"]
        if ts.get("converged", True):
            a(f"**Timestep.** The open-loop `pll_top` deck again at a "
              f"{ts['tmax_fine_s'] * 1e12:g} ps internal ceiling instead of "
              f"{run.TRAN_TMAX * 1e12:g} ps, as ratios to the campaign's own run: "
              f"conduction window {ts['t_on_ratio']:.4f}, slowest slew anywhere "
              f"{ts['slew_min_ratio']:.4f}, `CLK` slew {ts['clk_slew_ratio']:.4f}, "
              f"output frequency {ts['f_clk_ratio']:.6f}. A coarser chord under-states "
              "a slew and `edge_jitter` divides by it, so a ratio above 1 here is the "
              "campaign being the conservative one.")
        else:
            a(f"**Timestep — NOT ESTABLISHED.** The open-loop `pll_top` deck at a "
              f"{ts['tmax_fine_s'] * 1e12:g} ps internal ceiling instead of "
              f"{run.TRAN_TMAX * 1e12:g} ps does not converge on this ngspice build, "
              "at every rung of the same escalation ladder the campaign's own 25 ps "
              "grid uses (which converges at all 45 mandated points): the internal "
              "timestep collapses at the very first timepoint regardless of `gmin`. "
              "This is a limit of this one robustness check, not of the campaign's "
              "own measurement -- see the directory README.")
        a("")
        vh = val["vctrl_hold"]
        a(f"**The `VCTRL` hold.** {vh['r_hold_loose_ohm']:g} Ω in series instead of "
          f"{vh['r_hold_base_ohm']:g} Ω: conduction window {vh['t_on_ratio']:.4f}, "
          f"slowest slew {vh['slew_min_ratio']:.4f}, `CLK` slew "
          f"{vh['clk_slew_ratio']:.4f}, frequency {vh['f_clk_ratio']:.6f}; the "
          f"residual ripple on `VCTRL` goes from {vh['ripple_base_V'] * 1e6:.1f} µV to "
          f"{vh['ripple_loose_V'] * 1e6:.1f} µV. (The series resistance is there "
          "because `loop_filter` puts a 2 nF MIM capacitor directly across "
          "`VCTRL`, and a bare ideal source there stalls the solver.)")
        a("")
        sr = val["sense_resistance"]
        a(f"**The sense resistance, and the transimpedance correction.** The charge "
          f"pump's noise deck at {sr['rsense_hi_ohm']:g} Ω instead of "
          f"{sr['rsense_base_ohm']:g} Ω. The recovered short-circuit current noise "
          f"`S_v/|Z|²` must not depend on it: ratio {sr['s_i_ratio_at_1MHz']:.4f} at "
          f"1 MHz and {sr['s_i_ratio_at_grid_top']:.4f} at the grid top. The retired "
          f"`S_v/rsense²` reduction, on the same two runs, gives "
          f"{sr['naive_ratio_at_1MHz']:.4f} and {sr['naive_ratio_at_grid_top']:.4f} — "
          "i.e. it *does* depend on `rsense`, because above the node's own corner "
          "`rsense` is not the node's impedance. The correction the campaign "
          f"applies is {sr['correction_at_1MHz']:.4f}× at 1 MHz and "
          f"{sr['correction_at_grid_top']:.3g}× at the grid top; the anchor reads "
          f"{sr['anchor_ratio_at_grid_bottom']:.6f} at the bottom of the grid, which "
          "is the units check.")
        a("")
        nc = val["netlist_claims"]
        a("**What the netlist says, checked rather than asserted.**")
        a("")
        a(f"- Nets shared between two `pll_top` instances that step 1's enumeration "
          f"does not classify: `{nc['unclassified_shared_nets']}` (must be empty — "
          "an unclassified shared net would be a path this bound has not "
          "considered).")
        a(f"- Consumers of `LOCK`: `{nc['lock_detector_consumers']}` — the lock "
          "detector's only output reaches no other instance, which is what puts it "
          "in **no timing path** and reduces it to a load on `UP`/`DN`.")
        a("- Non-MOS leaf devices per block: "
          + ", ".join(f"{k} `{v}`" for k, v in sorted(nc["non_mos_devices"].items()))
          + " (all empty, so each block's MOS enumeration is its complete "
          "generator set).")
        a(f"- Cells characterized: `{nc['cells_characterized']}`; every one of them "
          "a single-stage leaf of the committed netlist: "
          f"**{nc['cells_characterized_are_single_stage']}**. (`xor2_3v3` is "
          "deliberately absent: it is three `nand2_3v3` stages, and self-biasing it "
          "reports its cascade's gain — 0.87 V of \"noise\" at 27 °C — which is a "
          "linearisation that has stopped being one, not a bound.)")
        a("- Declared timing-path stages, resolved against the netlist: "
          + ", ".join(f"{k} = {len(v)}" for k, v in sorted(nc["timing_paths"].items()))
          + ".")
        a("")
        tp = val["trip_point_dominance"]
        a("**Is the trip point the worst bias?** Per cell, the input offset at "
          "which its stationary output noise is largest, and the value there "
          "against the value at the trip point — the inequality `edge_jitter` "
          "rests on, measured across "
          + ", ".join(f"{v:+.2f} V" for v in run.CELL_BIAS_OFFSETS_V) + ".")
        a("")
        a("| Cell | worst offset (V) | σ_v at trip (mV) | σ_v worst (mV) | worst/trip |")
        a("|---|---|---|---|---|")
        for cell, v in sorted(tp.items()):
            a(f"| `{cell}` | {v['worst_offset_V']:+.2f} | "
              f"{v['sigma_v_at_trip_V'] * 1e3:.4f} | {v['sigma_v_worst_V'] * 1e3:.4f} | "
              f"{v['sigma_v_worst_V'] / v['sigma_v_at_trip_V']:.3f} |")
        a("")

    # --------------------------------------------------------- alignment
    if rows:
        res = [abs(r[2]["alignment"]["residual_s"]) for r in rows]
        lag = [r[2]["alignment"]["ref_lag_s"] for r in rows]
        a("## Is the deck in lock? (the two-pass reference alignment)")
        a("")
        a("The conduction window this bound gates the charge pump's noise by is a "
          "property of the LOCKED loop. An open-loop deck leaves `REF` and `FB` at "
          "whatever relative phase the free-running ring produces, and at an "
          "arbitrary phase the PFD asserts one output for the reset delay and the "
          "other for the reset delay **plus the phase error** — the wrong window by "
          "an order of magnitude. So every point runs the deck twice: once to find "
          "`FB`'s edges, then again with `REF` moved onto them.")
        a("")
        a(f"Over the {len(rows)} points, the first pass's `REF`-behind-`FB` lag was "
          f"{min(lag) * 1e9:.2f} … {max(lag) * 1e9:.2f} ns (of a 40 ns reference "
          f"period) and the second pass's residual separation "
          f"**{min(res) * 1e12:.2f} … {max(res) * 1e12:.2f} ps**, against the "
          f"{run.ALIGN_RESIDUAL_FRACTION:.0%}-of-`T_ref` ceiling a point is refused "
          "at. The conduction windows the aligned pass measures are "
          + f"{min(r[2]['t_on_s'] for r in rows) * 1e9:.3f} … "
          + f"{max(r[2]['t_on_s'] for r in rows) * 1e9:.3f} ns, a duty of "
          + f"{min(r[2]['t_on_s'] for r in rows) * 25e6 * 100:.2f} … "
          + f"{max(r[2]['t_on_s'] for r in rows) * 25e6 * 100:.2f} %.")
        a("")
        dr = [r[2]["divide_ratio_measured"] for r in rows]
        a(f"Measured divide ratio over the grid: {min(dr):.5f} … {max(dr):.5f} "
          "(6 by construction — the deck's own check that the divider is dividing "
          "and the alignment did not land on the wrong edge).")
        a("")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
