#!/usr/bin/env python3
"""Mint ``vco_bias_as_drawn_350.spice`` from the committed VCO export.

This campaign's second arm is a **counterfactual**: the bias generator as the
layout would have manufactured it before issue #381, when
``layout/pll_top/vco/primitives.poly_resistor()`` drew an unmarked
``ppolyf_u`` (350 ohm/sq) body for devices ``design/netlist/vco.spice``
declares as ``ppolyf_u_3k`` (3000 ohm/sq). Nothing else about that layout was
wrong, so the counterfactual netlist must differ from the committed export in
exactly one token per resistor and in nothing else.

Rather than hand-copy 25 device lines into the testbench fragment (which would
drift from the schematic the first time ``design/netlist.sh`` re-exports it),
this script *derives* the counterfactual: it lifts the ``vco_bias`` subckt out
of the committed export verbatim, renames it, and rewrites only the
``ppolyf_u_3k`` model token on the three ``X`` resistor lines. The result is
committed beside this script (``sim/`` is append-only evidence; a record must
be reproducible from committed files alone) and
``sim/tests/test_vco_bias_counterfactual.py`` re-runs this derivation and
fails if the committed file no longer matches -- so a future re-export of
``design/netlist/vco.spice`` cannot silently leave the counterfactual arm
describing a circuit the design no longer has.

    python3 sim/vco-bias-current/testbench/make_counterfactual.py [--check]
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
SOURCE = REPO_ROOT / "design" / "netlist" / "vco.spice"
TARGET = Path(__file__).resolve().parent / "vco_bias_as_drawn_350.spice"

SOURCE_SUBCKT = "vco_bias"
TARGET_SUBCKT = "vco_bias_as_drawn_350"
AS_SPECIFIED_MODEL = "ppolyf_u_3k"
AS_DRAWN_MODEL = "ppolyf_u"

HEADER = f"""* gf180-pll :: sim/vco-bias-current :: COUNTERFACTUAL bias generator
*
* GENERATED by sim/vco-bias-current/testbench/make_counterfactual.py from
* design/netlist/vco.spice's own `.subckt {SOURCE_SUBCKT}` -- do not edit by
* hand. Two mechanical edits, and no others:
*
*   1. `.subckt {SOURCE_SUBCKT}` -> `.subckt {TARGET_SUBCKT}`
*   2. the three bias resistors' model token
*      `{AS_SPECIFIED_MODEL}` -> `{AS_DRAWN_MODEL}` (3000 -> 350 ohm/sq)
*
* This is NOT a design alternative and must never be cited as one: it is the
* device the pre-#381 layout would have manufactured for the schematic's
* `{AS_SPECIFIED_MODEL}` declaration, instantiated so the resulting bias-current
* error can be measured instead of asserted. See issue #381 and
* spec/decision-records/DR-009-vco-bias-resistor-device-class.md.
"""


def extract_subckt(text: str, name: str) -> str:
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if re.match(rf"^\.subckt\s+{re.escape(name)}\s", line, re.IGNORECASE):
            start = i
            break
    if start is None:
        raise SystemExit(f"{SOURCE}: no '.subckt {name}' found")
    for j in range(start, len(lines)):
        if re.match(r"^\.ends\b", lines[j], re.IGNORECASE):
            return "\n".join(lines[start : j + 1]) + "\n"
    raise SystemExit(f"{SOURCE}: '.subckt {name}' is never closed by '.ends'")


def render() -> str:
    body = extract_subckt(SOURCE.read_text(), SOURCE_SUBCKT)
    body = re.sub(
        rf"^(\.subckt\s+){re.escape(SOURCE_SUBCKT)}\b",
        rf"\g<1>{TARGET_SUBCKT}",
        body,
        flags=re.IGNORECASE | re.MULTILINE,
    )
    body, n = re.subn(rf"\b{re.escape(AS_SPECIFIED_MODEL)}\b", AS_DRAWN_MODEL, body)
    if n != 3:
        raise SystemExit(
            f"expected exactly 3 '{AS_SPECIFIED_MODEL}' instances in "
            f"'.subckt {SOURCE_SUBCKT}', found {n} -- the schematic's bias "
            "resistor set changed; re-check this campaign before regenerating"
        )
    return HEADER + body


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the committed file differs from a fresh derivation",
    )
    args = parser.parse_args(argv)

    fresh = render()
    if args.check:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != fresh:
            print(
                f"{TARGET} is stale -- re-run "
                "'python3 sim/vco-bias-current/testbench/make_counterfactual.py'",
                file=sys.stderr,
            )
            return 1
        print(f"{TARGET.name}: up to date")
        return 0

    TARGET.write_text(fresh)
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
