#!/usr/bin/env bash
# gf180-pll :: shared helper -- assemble the full closed-loop PLL DUT netlist
# (VCO + PFD/CP + loop filter + feedback divider) for the two closed-loop
# campaigns that need it: sim/lock-time (#12) and sim/output-range (#12).
#
# The four blocks are each self-contained `.subckt ... .ends` bodies (per
# design/README.md's leaf-cell namespacing convention -- every block owns its
# own cell names, so concatenating them cannot collide), so "assembly" is
# just: netlist the PFD/CP fresh (it has no committed export, per
# design/netlist.sh's two-convention split) and cat it together with the
# three committed exports.
#
# Usage:
#   sim/lib/assemble_closed_loop.sh <repo-root> <outfile>
#
# Writes <outfile> = vco.spice + divider_chain.spice + lock_detector.spice +
# loop_filter.spice + a fresh pfd_cp export, deduplicating any shared leaf
# cell (DR-004) two of those exports both inline. Fails loudly if any
# committed export is missing (run design/netlist.sh first) or if the
# resulting file is missing one of the four top-level subckts a caller needs.

set -euo pipefail

REPO="$1"
OUT="$2"

VCO="${REPO}/design/netlist/vco.spice"
DIV="${REPO}/design/netlist/divider_chain.spice"
LF="${REPO}/design/netlist/loop_filter.spice"
LOCKDET="${REPO}/design/netlist/lock_detector.spice"

for f in "${VCO}" "${DIV}" "${LF}" "${LOCKDET}"; do
  [ -f "${f}" ] || {
    echo "ERROR: ${f} missing -- run design/netlist.sh first" >&2
    exit 1
  }
done

PFDCP_DIR="$(mktemp -d)"
trap 'rm -rf "${PFDCP_DIR}"' EXIT
( cd "${REPO}" && ./design/netlist.sh --top pfd_cp "${PFDCP_DIR}" >/dev/null )
PFDCP="${PFDCP_DIR}/dut.spice"
[ -f "${PFDCP}" ] || {
  echo "ERROR: pfd_cp export failed -- see design/netlist.sh --top pfd_cp output" >&2
  exit 1
}

{
  echo "* GENERATED by sim/lib/assemble_closed_loop.sh -- do not edit by hand"
  echo "* Concatenation of five independently-exported blocks (each a"
  echo "* self-contained .subckt body, per design/README.md leaf-cell"
  echo "* namespacing -- no cell name collides across blocks with DIFFERENT"
  echo "* bodies; the shared-cell list (DR-004: inv_3v3, nand2_3v3, ...) is"
  echo "* instantiated by more than one of these five exports, so its"
  echo "* .subckt definitions legitimately repeat byte-identically below --"
  echo "* stripped except for the first occurrence, see below):"
  echo "*   design/netlist/vco.spice            (#8)"
  echo "*   design/netlist/divider_chain.spice  (#11)"
  echo "*   design/netlist/lock_detector.spice  (#11)"
  echo "*   design/netlist/loop_filter.spice    (#10)"
  echo "*   pfd_cp, freshly exported             (#9, no committed export)"
  echo
  cat "${VCO}"
  echo
  cat "${DIV}"
  echo
  cat "${LOCKDET}"
  echo
  cat "${LF}"
  echo
  cat "${PFDCP}"
} >"${OUT}.raw"

# The shared-cell list (DR-004) is instantiated, and therefore independently
# inlined, by more than one of the five exports above (divider_chain.spice AND
# lock_detector.spice both carry their own copy of inv_3v3/nand2_3v3, byte-
# identical -- design/netlist.sh's own collision check already guarantees
# that). A flat concatenation would therefore redefine those .subckt names,
# which ngspice accepts with a "redefinition" warning but which is still
# worth removing rather than relying on: keep only the FIRST occurrence of
# any .subckt name, by name, across the whole assembly.
python3 - "${OUT}.raw" "${OUT}" <<'PYEOF'
import re, sys

src, dst = sys.argv[1], sys.argv[2]
text = open(src).read()
blocks = re.split(r'(?=^\.subckt )', text, flags=re.MULTILINE)
seen = set()
out = [blocks[0]]  # preamble before the first .subckt
for block in blocks[1:]:
    name = block.split(None, 2)[1].lower()
    if name in seen:
        continue
    seen.add(name)
    out.append(block)
open(dst, "w").write("".join(out))
PYEOF
rm -f "${OUT}.raw"

# Sanity: every subckt this assembly's top-level instantiations need must be
# present, and the collision the leaf-cell-naming convention forbids must not
# have silently occurred (two same-named subckts with different bodies).
for top in vco divider_chain loop_filter pfd_cp; do
  grep -qi "^\.subckt ${top} " "${OUT}" || {
    echo "ERROR: assembled netlist is missing .subckt ${top} -- see ${OUT}" >&2
    exit 1
  }
done
