#!/usr/bin/env python3
"""gf180-pll :: period-jitter :: random-bound -- results/*.json -> results/SUMMARY.md.

Formats; computes nothing that is not a ratio or an extremum of committed
numbers.  Every figure the README, DR-032 and `spec/pll.md` quote is in the
output of this script, so a reader can check a quoted value against the JSON
without re-running ngspice.

    sim/period-jitter/random-bound/summarize.py > sim/period-jitter/random-bound/results/SUMMARY.md
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RES = HERE / "results"
sys.path.insert(0, str(HERE))

import rb_extract  # noqa: E402
import run  # noqa: E402


def load(name):
    p = RES / name
    return json.loads(p.read_text()) if p.is_file() else None


def pct(x, nd=4):
    return f"{x:.{nd}f} %"


def main() -> int:
    points = run.load_points()
    cal = load("calibrate.json")
    loop = load("loop.json")
    rows, missing = [], []
    for name in points:
        tr, sid, tj = (load(f"transient_{name}.json"), load(f"sid_{name}.json"),
                       load(f"trajectory_{name}.json"))
        if not (tr and sid and tj):
            missing.append(name)
            continue
        rows.append((name, tr, sid, tj))
    ref = run.REFERENCE_POINT
    val = load(f"validate_{ref}.json")
    out: list[str] = []
    a = out.append
    a("<!-- GENERATED by sim/period-jitter/random-bound/summarize.py.")
    a("     Do not edit: regenerate with")
    a("       sim/period-jitter/random-bound/summarize.py \\")
    a("           > sim/period-jitter/random-bound/results/SUMMARY.md -->")
    a("")
    a("# Random period jitter, bounded — results")
    a("")
    a("An upper bound on the random (noise-driven) period jitter of the locked "
      "output at every point of the mandated 45-point PVT grid, against the "
      f"{run.BUDGET_PCT:.2f} % RMS that `spec/pll.md`'s supply-ripple derivation "
      "leaves for it. What the bound covers, and the three inequalities it "
      "rests on, are in the directory README and "
      "`spec/decision-records/DR-032-*.md`.")
    a("")
    if rows:
        env = rows[0][1]["environment"]
        a(f"- ngspice: `{env['ngspice']}`")
        a(f"- PDK models: `{env['pdk_models']}`")
        heads = sorted({r[1]["environment"]["repo_head"] for r in rows})
        a(f"- repo HEAD at run time: {', '.join(f'`{h}`' for h in heads)}")
        dirty = [r[0] for r in rows if r[1]["environment"]["repo_dirty"]]
        a(f"- design/ or this directory modified at run time: "
          f"{'**yes** at ' + ', '.join(dirty) if dirty else 'no, at every point'}")
        utc = sorted(r[1]["environment"]["run_utc"] for r in rows)
        a(f"- runs (UTC): {utc[0]} … {utc[-1]}")
    a(f"- points present: **{len(rows)} of {len(points)}**"
      + (f" — MISSING: {', '.join(missing)}" if missing else ""))
    a("")

    # ------------------------------------------------------------------ grid
    if rows:
        tot = [r[1]["bound"]["total_pct"] for r in rows]
        worst = max(rows, key=lambda r: r[1]["bound"]["total_pct"])
        a("## The bound, per point")
        a("")
        a(f"**Worst point: `{worst[0]}`, {pct(worst[1]['bound']['total_pct'])} "
          f"RMS** against the {run.BUDGET_PCT:.2f} % budget — a margin of "
          f"{run.BUDGET_PCT / worst[1]['bound']['total_pct']:.2f}×. "
          f"Range over the {len(rows)} points: {pct(min(tot))} … {pct(max(tot))}. "
          f"Points whose bound exceeds the budget: "
          f"**{sum(t > run.BUDGET_PCT for t in tot)}**.")
        a("")
        a("`σ̂` is the pooled period standard deviation of the noisy copies, "
          f"`σ₉₅` its one-sided {int(100 * rows[0][1]['confidence'])} % upper "
          "confidence limit (χ², `dof` = periods − copies). `floor` is the clean "
          "reference copy's own period spread in the same deck — the solver, "
          "not the circuit. `w` is the white loop factor (`white_loop_factor`). "
          "`VCO` = `σ₉₅·√w`, `LF` = the loop-filter resistor through the "
          "control node, `bound` = their quadrature sum; all in % of the period.")
        a("")
        a("| Point | f0 (MHz) | K_vco (MHz/V) | periods | σ̂ (ps) | σ₉₅ (ps) | "
          "floor (fs) | lag-1 ρ | w | VCO | LF | **bound** | margin |")
        a("|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        for name, tr, sid, tj in rows:
            n, b = tr["noisy"], tr["bound"]
            a(f"| `{name}` | {tj['f0_Hz'] / 1e6:.3f} | {tj['kvco_Hz_per_V'] / 1e6:.1f} | "
              f"{n['n_periods']} | {n['sigma_s'] * 1e12:.2f} | "
              f"{n['sigma_upper_s'] * 1e12:.2f} | {tr['floor']['sigma_s'] * 1e15:.1f} | "
              f"{n['lag1_autocorrelation']:+.3f} | {tr['white_loop_factor']:.4f} | "
              f"{b['vco_pct']:.4f} | {b['loop_filter_pct']:.4f} | "
              f"**{b['total_pct']:.4f}** | {run.BUDGET_PCT / b['total_pct']:.2f}× |")
        a("")

    # ------------------------------------------------------------ injection
    if rows:
        a("## What was injected, and at which bias (stage `sid`)")
        a("")
        a("Each generator's injection density is the maximum over its own "
          "trajectory of `S_white + Φ·S_flicker(F)` — white part plus the "
          "flicker part's white equivalent. The bias it was calibrated at is "
          "the argmax row in `results/sid_<point>.json` (`at_argmax`).")
        a("")
        a("`C/B` is the largest factor by which sampling a switching device at "
          "every 2.17 ps step (round C) raised its 17 ps maximum (round B) — the "
          "maximum's convergence against sampling resolution. `B/A` is the same "
          "for 17 ps against the 48-phase round A. `bias span` is the largest "
          "round-A max/min of any bias-generator device, which is also the "
          "margin its injection density is raised by.")
        a("")
        a("| Point | units anchor | I_d reproduction | Φ (by exponent) | "
          "evaluated A / B / C | max C/B | max B/A | max bias span (dB) | "
          "Σ S_inj ring / bias / buffer (A²/Hz) |")
        a("|---|---|---|---|---|---|---|---|---|")
        for name, tr, sid, tj in rows:
            dv = sid["devices"]
            sw = [v for v in dv.values() if v["block"] in ("ring", "buffer")]
            gcb = max(v["gain_c_over_b"] for v in sw)
            gba = max(v["gain_b_over_a"] for v in sw)
            span = max((v["round_a_span_dB"] or 0.0) for v in dv.values()
                       if v["block"] == "bias")
            inj = sid["S_inj_A2_per_Hz"]
            blk = {b: sum(inj[k] for k, v in dv.items() if v["block"] == b)
                   for b in ("ring", "bias", "buffer")}
            phi = ", ".join(f"{p['alpha']:.2f}→{p['phi']:.2f}" for p in sid["phi"])
            lo, hi = sid["units_anchor_range"]
            ne = sid["n_evaluated"]
            a(f"| `{name}` | {lo:.7f}–{hi:.7f} | ≤ {sid['repro_worst_id_rel']:.1e} | {phi} | "
              f"{ne['A']} / {ne['B']} / {ne['C']} | {gcb:.4f} | {gba:.3f} | {span:.3f} | "
              f"{blk['ring']:.2e} / {blk['bias']:.2e} / {blk['buffer']:.2e} |")
        a("")
        # the reference point's largest generators
        r0 = next((r for r in rows if r[0] == ref), None)
        if r0:
            dv = r0[2]["devices"]
            top = sorted(dv.items(), key=lambda kv: -kv[1]["S_equiv_max"])[:12]
            a(f"### The twelve largest injection densities at `{ref}`")
            a("")
            a("| Device | block | model | argmax phase | V_gs (V) | V_ds (V) | I_d (A) | "
              "S_white | S_flicker(F) | α | Φ | S_inj |")
            a("|---|---|---|---|---|---|---|---|---|---|---|---|")
            for k, v in top:
                m = v["at_argmax"]
                b = m.get("bias", {})
                a(f"| `{k}` | {v['block']} | {v['model']} | {v['argmax_phase']:.4f} | "
                  f"{b.get('vgs', float('nan')):.3f} | {b.get('vds', float('nan')):.3f} | "
                  f"{b.get('id', float('nan')):.3e} | {m['S_white']:.2e} | "
                  f"{m['S_flicker_F']:.2e} | {m['alpha'] if m['alpha'] is None else round(m['alpha'], 4)} | "
                  f"{m['phi']:.2f} | {v['S_equiv_max']:.2e} |")
            a("")

    # ------------------------------------------------------------ calibration
    if cal:
        a("## Is `trnoise` the density it is asked for? (stage `calibrate`)")
        a("")
        a(f"Four sources into `R = {cal['R_ohm']:g} Ω ∥ C = {cal['C_F']:g} F` "
          f"(τ = 1 ns) over {cal['tstop_s'] * 1e6:g} µs; expected variance "
          "`S R / (4C)` with `S = 2 NA² NT` one-sided. "
          f"{cal['effective_independent_samples']:.0f} effective samples.")
        a("")
        a("| source | NT (ps) | measured / expected | statistical ±1σ |")
        a("|---|---|---|---|")
        for s in cal["sources"]:
            a(f"| {s['source']} | {s['NT_s'] * 1e12:g} | {s['measured_over_theory']:.4f} | "
              f"{s['rel_std_error']:.4f} |")
        mean = sum(s["measured_over_theory"] for s in cal["sources"]) / len(cal["sources"])
        a("")
        a(f"Mean {mean:.4f}. Correlation between two instances: "
          f"{cal['corr_a_b']:+.4f} (±{cal['corr_expected_std']:.4f} expected for "
          "independent sources).")
        a("")

    # ------------------------------------------------------------ loop
    if loop:
        f, e = loop["envelope_freqs_Hz"], loop["envelope"]
        f0 = 150e6
        t_w = (1 + rb_extract.WINDOW_MARGIN) / f0
        a("## The loop (stage `loop`)")
        a("")
        a(f"{loop['n_loops']} loops `T = A Z(s)/s` over the as-built filter's "
          f"R ∈ {loop['filter_R_ohm'][0] / 1e3:.1f}…{loop['filter_R_ohm'][1] / 1e3:.1f} kΩ, "
          f"C1 ∈ {loop['filter_C1_F'][0] * 1e12:.1f}…{loop['filter_C1_F'][1] * 1e12:.1f} pF, "
          f"C2 ∈ {loop['filter_C2_F'][0] * 1e12:.2f}…{loop['filter_C2_F'][1] * 1e12:.2f} pF, "
          f"every gain with PM ≥ {loop['pm_floor_deg']:g}° (crossovers "
          f"{loop['fc_range_Hz'][0] / 1e3:.1f} kHz … {loop['fc_range_Hz'][1] / 1e6:.3f} MHz).")
        a("")
        a(f"- peak of the error-transfer envelope `max |1/(1+T)|²`: "
          f"**{loop['peak_sq']:.3f}** at {loop['peak_at_Hz'] / 1e6:.3f} MHz — the naive "
          "closed-loop factor, NOT the one used")
        a(f"- white loop factor at 150 MHz: **{rb_extract.white_loop_factor(f, e, t_w):.4f}**")
        for al in (0.95, 1.0, 1.12):
            a(f"- flicker factor Φ at α = {al:g}, F = {0.475 * f0 / 1e6:.2f} MHz: "
              f"**{rb_extract.flicker_factor(al, 0.475 * f0, t_w, f, e):.3f}**")
        a(f"- open-loop Φ at α = 0.95 for comparison: "
          f"{rb_extract.flicker_factor_open_loop(0.95):.2f}; at α = 1.12: diverges")
        kt = loop["kt_over_c_var_V2_by_temp"]
        a("- loop-filter `kT·C1/(C2(C1+C2))` (V²): " + ", ".join(
            f"{k} °C → {v:.3e} ({math.sqrt(v) * 1e6:.1f} µV RMS)" for k, v in kt.items()))
        a("")

    # ------------------------------------------------------------ validation
    if val:
        a(f"## Is the transient converged and linear? (stage `validate`, `{ref}`)")
        a("")
        b = val["base"]
        a("Each variant is an independent deck of the transient stage's own shape, "
          "compared statistically with that stage's result at this point "
          f"(`base`: σ̂ = {b['sigma_s'] * 1e12:.3f} ps over {b['n_periods']} periods). "
          "`± 1σ` is the ratio's standard error from the two estimates' degrees of "
          "freedom.")
        a("")
        want = {"repeat": "1", "fine_tmax": "1 (timestep converged)",
                "nt5": "1 (source white)", "nt20": "1 (source white)",
                "x3": f"{run.VAL_SCALE:g} (linear)", "white": "share of `base`",
                "ring": "share", "bias": "share", "buffer": "share"}
        a("| variant | what changes | periods | σ̂ (ps) | σ̂ / base | ± 1σ | expected |")
        a("|---|---|---|---|---|---|---|")
        what = {"repeat": "nothing", "fine_tmax": "timestep ceiling 2.5 ps",
                "nt5": "`trnoise` NT = 5 ps", "nt20": "`trnoise` NT = 20 ps",
                "x3": "every amplitude × 3", "white": "flicker parts removed",
                "ring": "ring generators only", "bias": "bias-generator generators only",
                "buffer": "output-buffer generators only"}
        for k, r in val["runs"].items():
            q = val["ratios"][k]
            s_ = r["summary"]
            a(f"| `{k}` | {what[k]} | {s_['n_periods']} | {s_['sigma_s'] * 1e12:.3f} | "
              f"{q['ratio']:.3f} | {q['se']:.3f} | {want[k]} |")
        a("")
        sh = val["block_shares_of_variance"]
        a(f"Shares of `base`'s variance: ring {sh['ring']:.3f}, bias generator "
          f"{sh['bias']:.3f}, output buffer {sh['buffer']:.3f} — sum "
          f"**{val['block_shares_sum']:.3f}** (1 for independent generators in a "
          f"linear circuit); white generators alone {sh['white']:.3f}.")
        a("")
        rep = val["repeat_vs_transient_same_seed"]
        a("Same deck, same `rndseed`, run twice — period-by-period correlation of "
          "the two runs' noisy copies: " + ", ".join(f"{p['corr']:+.3f}" for p in rep)
          + ". A realisation is **not** reproduced by fixing the seed on this build, "
          "which is why every comparison above is statistical.")
        a("")
        forms = val.get("noise_deck_forms")
        if forms:
            a("Noise deck — the summed, multi-phase form `sid` runs, against one "
              "`.noise` per device on a single-phase deck, at phase "
              f"{forms['phase']:.4f} (selected by `{forms['selected_by']}`); largest "
              "relative difference over all 62 MOS devices and both frequencies: "
              + ", ".join(f"`{k}` {v:.1e}" for k, v in sorted(forms["max_rel_diff"].items()))
              + ".")
            a("")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
