#!/usr/bin/env bash
# gf180-pll :: export the xschem schematics to ngspice subcircuit netlists.
#
#   ./design/netlist.sh          # regenerate design/netlist/*.spice
#   ./design/netlist.sh --check  # regenerate into a temp dir and diff (CI-safe)
#
# Every top cell listed in BLOCKS is netlisted with its full hierarchy into one
# self-contained file under design/netlist/. xschem emits the *top* cell's port
# list as a commented `**.subckt` header (because the top of a netlist run is
# normally a testbench), so the two sed rules below promote it to a real
# `.subckt` / `.ends` pair and drop the trailing `.end` -- the file is then
# `.include`-able by a testbench deck. That post-processing is the whole of it:
# no other line of the xschem output is altered, so each committed netlist stays
# a faithful rendering of its schematic.
#
# Never `.include` two of these files in the same deck: each carries its own
# copy of the shared leaf cells (inv_3v3, nand2_3v3, vco_stage, ...), so
# including two would redefine them.
#
# `--check` also runs a cross-block leaf-cell collision check (see
# check_leaf_cell_collisions below): every one of design/netlist/*.spice is a
# self-contained export that inlines its own copy of every leaf cell it uses,
# captured whenever that top was last regenerated. Two tops can therefore
# commit genuinely different bodies under the same `.subckt <name>` even
# though design/ only ever holds one `<name>.sch` at a time on disk -- that's
# exactly the add/add-collision hazard this repo has hit twice (see
# design/README.md "Leaf-cell ownership and naming"). The check hashes every
# `.subckt ... .ends` block across all committed exports and fails loudly if
# the same cell name hashes differently anywhere.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Top cells a testbench instantiates: the ring VCO (#8) and the feedback
# divider / lock detector (#11).
BLOCKS=(vco div23_cell divider_chain lock_detector dff_tg_3v3)

command -v xschem >/dev/null 2>&1 || {
  echo "ERROR: xschem not found on PATH" >&2
  exit 1
}

XSCHEM_VERSION="$(xschem --no_x -q --version 2>/dev/null | head -1 || echo 3.4.7)"

# Two-line banner prepended to each export. `vco.spice` and the divider /
# lock-detector exports were minted by two different generations of this script
# and carry different wording; both are reproduced verbatim on purpose. The
# `sim/` evidence records pin the SHA-256 of the netlist each campaign actually
# simulated, and the committed exports still hash equal to those snapshots --
# rewording a comment line would break that chain for no benefit.
banner() {
  case "$1" in
    vco)
      printf '%s\n' \
        "* gf180-pll :: VCO netlist exported from design/vco.sch by design/netlist.sh" \
        "* Do not edit by hand -- edit the schematics and re-run design/netlist.sh."
      ;;
    *)
      printf '%s\n' \
        "* gf180-pll :: $1 -- generated by design/netlist.sh from $1.sch" \
        "* xschem ${XSCHEM_VERSION}; do not edit by hand."
      ;;
  esac
}

# xschem stamps the absolute path of every .sch/.sym it expands into a comment
# (`** sch_path: /abs/checkout/design/foo.sch`). That path is whichever checkout
# the file was generated in, so a byte-exact `--check` would call every clone
# but the original stale. Those comment lines -- and only those -- are rewritten
# to repo-relative form on both sides of the comparison; every other byte,
# including everything ngspice reads, is still compared exactly.
#
# Writes to a file rather than a pipeline so that a sed failure aborts the run
# (`set -e`) instead of silently producing two empty streams that compare equal.
normalize() {
  sed -E 's#^(\*\* (sch|sym)_path: ).*/design/#\1design/#' "$1" >"$2"
}

sha256_of_stdin() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print $1}'
  else
    shasum -a 256 | awk '{print $1}'
  fi
}

# Extracts every `.subckt <name> ... .ends` block from a committed netlist
# export and records a content hash for each, so the same leaf-cell name can
# be compared across every top in BLOCKS that defines it. `celldir` gets one
# file per cell name, appended with one `<top>\t<hash>` line per top that
# defines that cell -- if a cell's hash set ever has more than one distinct
# value, two tops disagree about what that cell is.
record_subckt_hashes() {
  local blk="$1" file="$2" celldir="$3" name hash
  while IFS= read -r name; do
    [ -n "${name}" ] || continue
    hash="$(awk -v n="${name}" '
              $0 ~ "^\\.subckt " n "( |$)" { capturing=1 }
              capturing { print }
              /^\.ends/ && capturing { exit }
            ' "${file}" | sha256_of_stdin)"
    printf '%s\t%s\n' "${blk}" "${hash}" >>"${celldir}/${name}"
  done < <(grep '^\.subckt ' "${file}" | awk '{print $2}')
}

# Fails loudly if any leaf-cell name resolves to genuinely different content
# across the committed exports of the tops in BLOCKS -- the mechanical guard
# for the add/add-collision hazard described in the header comment above and
# in design/README.md's "Leaf-cell ownership and naming" section. Byte-
# identical content under the same name across tops is expected and not a
# failure; only a real content divergence is.
check_leaf_cell_collisions() {
  local celldir cellfile cellname nuniq rc=0
  celldir="$(mktemp -d)"

  for blk in "${BLOCKS[@]}"; do
    local committed="${HERE}/netlist/${blk}.spice"
    [ -f "${committed}" ] || continue
    record_subckt_hashes "${blk}" "${committed}" "${celldir}"
  done

  for cellfile in "${celldir}"/*; do
    [ -e "${cellfile}" ] || continue
    cellname="$(basename "${cellfile}")"
    nuniq="$(awk -F'\t' '{print $2}' "${cellfile}" | sort -u | wc -l | tr -d ' ')"
    if [ "${nuniq}" -gt 1 ]; then
      echo "ERROR: leaf-cell '${cellname}' diverges across BLOCKS tops (add/add collision):" >&2
      awk -F'\t' '{print "  " $1 " -> " $2}' "${cellfile}" | sort -u >&2
      rc=1
    fi
  done

  rm -rf "${celldir}"
  return "${rc}"
}

export_block() {
  local blk="$1" outdir="$2" work="$3"

  # -n netlist, -s spice format, -q quit when done, --no_x no GUI, -o out dir.
  # xschem 3.4.7 can exit non-zero on a successful `-q` batch netlist, so the
  # exit status is deliberately ignored; the netlist file's existence is the
  # success check.
  (cd "${HERE}" && xschem --no_x -n -s -q \
      --rcfile "${HERE}/xschemrc" -o "${work}" "${HERE}/${blk}.sch" >/dev/null 2>&1) || true

  [ -f "${work}/${blk}.spice" ] || {
    echo "ERROR: xschem produced no netlist for ${blk} at ${work}/${blk}.spice" >&2
    exit 1
  }

  {
    banner "${blk}"
    sed -e 's/^\*\*\.subckt/.subckt/' \
        -e 's/^\*\*\.ends/.ends/' \
        -e '/^\.end$/d' \
        "${work}/${blk}.spice"
  } >"${outdir}/${blk}.spice"
}

WORK="$(mktemp -d)"
GENDIR="$(mktemp -d)"
trap 'rm -rf "${WORK}" "${GENDIR}"' EXIT

for blk in "${BLOCKS[@]}"; do
  [ -f "${HERE}/${blk}.sch" ] || {
    echo "ERROR: no schematic at design/${blk}.sch" >&2
    exit 1
  }
  export_block "${blk}" "${GENDIR}" "${WORK}"
done

if [ "${1:-}" = "--check" ]; then
  rc=0
  for blk in "${BLOCKS[@]}"; do
    committed="${HERE}/netlist/${blk}.spice"
    if [ ! -f "${committed}" ]; then
      echo "STALE: design/netlist/${blk}.spice is missing -- run design/netlist.sh" >&2
      rc=1
      continue
    fi
    normalize "${committed}" "${WORK}/${blk}.committed.norm"
    normalize "${GENDIR}/${blk}.spice" "${WORK}/${blk}.regen.norm"
    if ! diff -u --label "design/netlist/${blk}.spice (committed)" \
                 --label "design/${blk}.sch (regenerated)" \
                 "${WORK}/${blk}.committed.norm" "${WORK}/${blk}.regen.norm"; then
      echo "STALE: design/netlist/${blk}.spice differs from ${blk}.sch" >&2
      rc=1
    fi
  done

  if ! check_leaf_cell_collisions; then
    rc=1
  fi

  if [ "${rc}" -eq 0 ]; then
    echo "design/netlist.sh --check: all ${#BLOCKS[@]} netlists match the schematics, no leaf-cell collisions"
  else
    echo "ERROR: design/netlist.sh --check failed -- see STALE / leaf-cell collision errors above" >&2
  fi
  exit "${rc}"
fi

mkdir -p "${HERE}/netlist"
for blk in "${BLOCKS[@]}"; do
  cp "${GENDIR}/${blk}.spice" "${HERE}/netlist/${blk}.spice"
  echo "netlisted ${blk} -> design/netlist/${blk}.spice"
done
