#!/usr/bin/env bash
# gf180-pll :: export the xschem schematics to ngspice subcircuit netlists.
#
#   ./design/netlist.sh          # regenerate design/netlist/*.spice
#   ./design/netlist.sh --check  # regenerate into a temp dir and diff (CI-safe)
#
# Every top cell listed in BLOCKS is netlisted with its full hierarchy into one
# self-contained file under design/netlist/. xschem emits the *top* cell's port
# list as a commented `**.subckt` header (because the top of a netlist run is
# normally a testbench), so the two sed rules below promote it to a real
# `.subckt` / `.ends` pair and drop the trailing `.end` -- the file is then
# `.include`-able by a testbench deck. That post-processing is the whole of it:
# no other line of the xschem output is altered, so each committed netlist stays
# a faithful rendering of its schematic.
#
# Never `.include` two of these files in the same deck: each carries its own
# copy of the shared leaf cells (inv_3v3, nand2_3v3, vco_stage, ...), so
# including two would redefine them.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Top cells a testbench instantiates: the ring VCO (#8) and the feedback
# divider / lock detector (#11).
BLOCKS=(vco div23_cell divider_chain lock_detector dff_tg_3v3)

command -v xschem >/dev/null 2>&1 || {
  echo "ERROR: xschem not found on PATH" >&2
  exit 1
}

XSCHEM_VERSION="$(xschem --no_x -q --version 2>/dev/null | head -1 || echo 3.4.7)"

# Two-line banner prepended to each export. `vco.spice` and the divider /
# lock-detector exports were minted by two different generations of this script
# and carry different wording; both are reproduced verbatim on purpose. The
# `sim/` evidence records pin the SHA-256 of the netlist each campaign actually
# simulated, and the committed exports still hash equal to those snapshots --
# rewording a comment line would break that chain for no benefit.
banner() {
  case "$1" in
    vco)
      printf '%s\n' \
        "* gf180-pll :: VCO netlist exported from design/vco.sch by design/netlist.sh" \
        "* Do not edit by hand -- edit the schematics and re-run design/netlist.sh."
      ;;
    *)
      printf '%s\n' \
        "* gf180-pll :: $1 -- generated by design/netlist.sh from $1.sch" \
        "* xschem ${XSCHEM_VERSION}; do not edit by hand."
      ;;
  esac
}

# xschem stamps the absolute path of every .sch/.sym it expands into a comment
# (`** sch_path: /abs/checkout/design/foo.sch`). That path is whichever checkout
# the file was generated in, so a byte-exact `--check` would call every clone
# but the original stale. Those comment lines -- and only those -- are rewritten
# to repo-relative form on both sides of the comparison; every other byte,
# including everything ngspice reads, is still compared exactly.
#
# Writes to a file rather than a pipeline so that a sed failure aborts the run
# (`set -e`) instead of silently producing two empty streams that compare equal.
normalize() {
  sed -E 's#^(\*\* (sch|sym)_path: ).*/design/#\1design/#' "$1" >"$2"
}

export_block() {
  local blk="$1" outdir="$2" work="$3"

  # -n netlist, -s spice format, -q quit when done, --no_x no GUI, -o out dir.
  # xschem 3.4.7 can exit non-zero on a successful `-q` batch netlist, so the
  # exit status is deliberately ignored; the netlist file's existence is the
  # success check.
  (cd "${HERE}" && xschem --no_x -n -s -q \
      --rcfile "${HERE}/xschemrc" -o "${work}" "${HERE}/${blk}.sch" >/dev/null 2>&1) || true

  [ -f "${work}/${blk}.spice" ] || {
    echo "ERROR: xschem produced no netlist for ${blk} at ${work}/${blk}.spice" >&2
    exit 1
  }

  {
    banner "${blk}"
    sed -e 's/^\*\*\.subckt/.subckt/' \
        -e 's/^\*\*\.ends/.ends/' \
        -e '/^\.end$/d' \
        "${work}/${blk}.spice"
  } >"${outdir}/${blk}.spice"
}

WORK="$(mktemp -d)"
GENDIR="$(mktemp -d)"
trap 'rm -rf "${WORK}" "${GENDIR}"' EXIT

for blk in "${BLOCKS[@]}"; do
  [ -f "${HERE}/${blk}.sch" ] || {
    echo "ERROR: no schematic at design/${blk}.sch" >&2
    exit 1
  }
  export_block "${blk}" "${GENDIR}" "${WORK}"
done

if [ "${1:-}" = "--check" ]; then
  rc=0
  for blk in "${BLOCKS[@]}"; do
    committed="${HERE}/netlist/${blk}.spice"
    if [ ! -f "${committed}" ]; then
      echo "STALE: design/netlist/${blk}.spice is missing -- run design/netlist.sh" >&2
      rc=1
      continue
    fi
    normalize "${committed}" "${WORK}/${blk}.committed.norm"
    normalize "${GENDIR}/${blk}.spice" "${WORK}/${blk}.regen.norm"
    if ! diff -u --label "design/netlist/${blk}.spice (committed)" \
                 --label "design/${blk}.sch (regenerated)" \
                 "${WORK}/${blk}.committed.norm" "${WORK}/${blk}.regen.norm"; then
      echo "STALE: design/netlist/${blk}.spice differs from ${blk}.sch" >&2
      rc=1
    fi
  done
  if [ "${rc}" -eq 0 ]; then
    echo "design/netlist.sh --check: all ${#BLOCKS[@]} netlists match the schematics"
  else
    echo "ERROR: committed netlists are stale -- re-run design/netlist.sh" >&2
  fi
  exit "${rc}"
fi

mkdir -p "${HERE}/netlist"
for blk in "${BLOCKS[@]}"; do
  cp "${GENDIR}/${blk}.spice" "${HERE}/netlist/${blk}.spice"
  echo "netlisted ${blk} -> design/netlist/${blk}.spice"
done
