"""Deck composition and ngspice execution for one PVT point."""

from __future__ import annotations

import re
import shutil
import string
import subprocess
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
from pathlib import Path

from .corners import PvtPoint
from .derived import DerivedError, PointView, RawFile, derive_point_measures
from .pdk import Pdk
from .testbench import Phase, Testbench

NGSPICE = "ngspice"
DEFAULT_TIMEOUT_S = 300

# `print` output for a length-1 vector: "m_vout = 6.9043645202e-01"
_MEAS_LET_RE = re.compile(r"^\s*m_(\w+)\s*=\s*([-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?)\s*$")
_ERROR_RE = re.compile(r"^\s*(?:Error|ERROR|Fatal|fatal error|doAnalyses:)", re.MULTILINE)


class NgspiceMissing(RuntimeError):
    pass


def ngspice_version() -> str:
    exe = shutil.which(NGSPICE)
    if not exe:
        raise NgspiceMissing(
            "ngspice not found on PATH.\n"
            "  macOS:  brew install ngspice\n"
            "  Debian: apt-get install ngspice"
        )
    out = subprocess.run(
        [exe, "--version"], capture_output=True, text=True, check=False
    ).stdout
    for line in out.splitlines():
        if "ngspice-" in line:
            return line.strip().lstrip("* ").strip()
    return out.strip().splitlines()[0] if out.strip() else "unknown"


class _KeepUnknown(dict):
    """``format_map`` helper: leave a placeholder alone if we cannot fill it."""

    def __missing__(self, key):
        return "{" + key + "}"


def substitute_params(text: str, params: dict) -> str:
    """Fill ``{name}`` placeholders in ``text`` from the point's parameters.

    Needed for ``analyses``: ngspice's ``.control`` block is not a netlist
    line, so a ``tran {ktstep} {ktstop}`` there is *not* resolved against
    ``.param`` the way the same text is in a top-level ``.tran`` directive --
    it reaches ngspice verbatim and fails with "TSTEP is invalid". Every
    campaign whose timestep and stop time are functions of a swept rate
    (``ktstep = 1/(250*kf)``, ``ktstop = 12/kf``) needs those numbers spliced
    in per point, which is exactly what this does.

    Unknown placeholders are left untouched rather than raising, so a manifest
    that legitimately hands braces through to ngspice keeps working.
    """
    if "{" not in text:
        return text
    try:
        return string.Formatter().vformat(text, (), _KeepUnknown(params))
    except (IndexError, ValueError):  # pragma: no cover - malformed braces
        return text


def compose_deck(
    tb: Testbench, pdk: Pdk, point: PvtPoint, phase: Phase | None = None
) -> str:
    """Build the complete, self-contained ngspice deck for one PVT point.

    ``phase`` is one deck of a manifest that declares ``phases`` (see
    ``testbench.Phase``). It defaults to the testbench's first phase, which for
    every single-deck manifest is the *only* phase -- the implicit, unnamed one
    built from the top-level keys -- so the deck this produces is unchanged.
    """
    phase = phase or tb.run_phases[0]
    lines: list[str] = [
        f"* {tb.name} @ {phase.run_id(point.corner_id)} -- GENERATED by sim/harness, do not edit",
        f"* corner={point.corner.name} ({point.corner.description})",
        f"* temp={point.temp_c} C  vdd={point.vdd} V  pdk={pdk.variant}@{pdk.version}",
    ]
    if phase.name:
        lines.append(
            f"* phase={phase.name}"
            + (f" ({phase.description})" if phase.description else "")
            + f" -- one of {len(tb.run_phases)} decks this record is minted from"
        )
    lines += [
        "",
        "* ---- PVT parameters -------------------------------------------------",
        f".param vdd_nom={tb.nominal_supply_v!r}",
        f".param vdd_val={point.vdd!r}",
        f".param temp_c={point.temp_c!r}",
    ]
    for key, value in tb.params.items():
        lines.append(f".param {key}={value}")
    # A phase's own params come after the manifest's shared ones (so a phase
    # overrides rather than restates them) and before the axis params (so an
    # axis can still override everything, as documented).
    if phase.params:
        lines.append("")
        lines.append(f"* ---- phase {phase.name} parameters")
        for key, value in phase.params.items():
            lines.append(f".param {key}={value}")
    # Per-point parameters from the extra sweep axes come *after* the manifest's
    # fixed params, so an axis can override a default rather than being forced
    # to name a parameter no fixed entry uses.
    axis_params = point.params
    if axis_params:
        lines.append("")
        lines.append(
            "* ---- sweep axes: "
            + ", ".join(f"{axis}={pid}" for axis, pid in point.axes.items())
        )
        for key, value in axis_params.items():
            lines.append(f".param {key}={value}")

    lines += [
        "",
        "* ---- gf180mcu models ------------------------------------------------",
        f'.include "{pdk.design_include}"',
    ]
    for section in point.corner.sections:
        lines.append(f'.lib "{pdk.model_lib}" {section}')
    # Corner-independent sections the bundles do not carry (see
    # testbench._load_extra_lib_sections): added at every PVT point, after the
    # corner's own sections, so they cannot pin a corner-varying axis.
    for section in tb.extra_lib_sections:
        lines.append(f'.lib "{pdk.model_lib}" {section}')

    lines += [
        "",
        f".temp {point.temp_c!r}",
    ]
    for option in tuple(tb.options) + tuple(phase.options):
        lines.append(f".options {option}")

    # tb.resolved_dut resolves a `dut_export` (design/netlist.sh --top <top>)
    # on first access, here or in write_netlist_snapshot()/provenance() --
    # whichever runs first for this Testbench instance. See
    # Testbench.resolved_dut / DutExportSpec.resolve().
    dut_sources = tb.resolved_dut
    if dut_sources:
        lines += [
            "",
            "* ---- DUT (composed at run time) --------------------------------------",
        ]
        lines += [f'.include "{path}"' for path in dut_sources]

    lines += [
        "",
        "* ---- testbench ------------------------------------------------------",
        f'.include "{phase.netlist}"',
    ]

    if phase.raw_measures:
        lines += ["", "* ---- measurements (raw .measure pass-through) ------------------------"]
        for name, rm in phase.raw_measures.items():
            lines.append(f".measure {rm.analysis} {name} {rm.expr}")

    lines += [
        "",
        "* ---- measurement ----------------------------------------------------",
        ".control",
        "set numdgt=10",
        "set noaskquit",
    ]
    substitutions = {
        "vdd_val": point.vdd,
        "vdd_nom": tb.nominal_supply_v,
        "temp_c": point.temp_c,
        **{str(k): v for k, v in tb.params.items()},
        **{str(k): v for k, v in phase.params.items()},
        **axis_params,
    }
    lines += [
        f"  {substitute_params(analysis, substitutions)}" for analysis in phase.analyses
    ]
    for name, expr in phase.measure.items():
        lines.append(f"  let m_{name} = {expr}")
    for name in phase.measure:
        lines.append(f"  print m_{name}")
    if tb.raw_measures:
        # Netlist-level `.measure` cards (emitted above) are serviced by
        # ngspice's *own* post-`.control` re-run of every `.analyses` line --
        # a second full transient/AC/etc pass that reproduces exactly the
        # measurements already taken during the `.control` block's own run of
        # those same analyses (see `analysis` on RawMeasure / the module
        # docstring's `raw_measures` entry). `quit` here ends the ngspice
        # session at the close of the `.control` block, before that
        # redundant pass ever starts, so every campaign that declares
        # `raw_measures` pays for its transient once instead of twice. Must
        # come after the `let`/`print` lines above (those read the analyses'
        # own results, and both are no-ops after `quit`); harmless when
        # `tb.measure` is also set (the `let`/`print` lines already ran).
        lines.append("  quit")
    lines += [".endc", ".end", ""]
    return "\n".join(lines)


@dataclass
class PhaseRun:
    """One deck's ngspice invocation at one PVT point.

    A single-deck manifest produces exactly one of these per point and the
    record does not mention them; a manifest that declares ``phases`` produces
    one per deck, and the record lists them so a reader can find the log of the
    deck a given measurement came from.
    """

    name: str                                     # "" for the implicit phase
    status: str                                   # "ok" | "failed" | "error"
    deck: str
    log: str
    seconds: float = 0.0
    message: str = ""

    def as_dict(self) -> dict:
        record = {
            "phase": self.name,
            "status": self.status,
            "deck": self.deck,
            "log": self.log,
            "seconds": round(self.seconds, 3),
        }
        if self.message:
            record["message"] = self.message
        return record


@dataclass
class _PhaseOutcome:
    """Everything one phase contributed to its point (internal to the runner)."""

    run: PhaseRun
    measurements: dict[str, float] = field(default_factory=dict)
    missing: list[str] = field(default_factory=list)
    raw_files: dict[str, RawFile] = field(default_factory=dict)
    raw_missing: list[str] = field(default_factory=list)
    not_measured: list[str] = field(default_factory=list)


@dataclass
class PointResult:
    point: PvtPoint
    status: str                                   # "ok" | "failed" | "error"
    measurements: dict[str, float] = field(default_factory=dict)
    missing: list[str] = field(default_factory=list)
    #: Declared *optional* (or derived) measurements that produced no value at
    #: this point. This is data -- "the flag never asserted", "the ladder never
    #: tripped" -- not an error, and it never costs the point its other
    #: measurements.
    not_measured: list[str] = field(default_factory=list)
    #: Files the manifest's ``raw_files`` declares, resolved for this point --
    #: whether or not the deck actually wrote them (see ``RawFile.exists()``).
    #: Carried on the result, not just handed to ``derive_point``, so
    #: ``derive_tables`` can reach every point's raw output too.
    raw_files: dict[str, RawFile] = field(default_factory=dict)
    #: Declared raw files this point's deck never wrote. Data, not an error:
    #: an early convergence failure legitimately produces no waveform, and the
    #: reduction over it is then recorded as not-measured -- the same treatment
    #: a derived measure that finds nothing to reduce already gets.
    raw_files_missing: list[str] = field(default_factory=list)
    seconds: float = 0.0
    #: The point's *first* deck and log. A single-deck manifest has only one,
    #: which is why these stay scalars; a phased manifest reports every deck in
    #: :attr:`phases` as well, and the record renders that list.
    deck: str = ""
    log: str = ""
    message: str = ""
    #: One entry per deck this point ran, in phase order. Length 1 (and unnamed)
    #: for every manifest that does not declare ``phases``.
    phases: tuple[PhaseRun, ...] = ()

    def as_dict(self) -> dict:
        record = self.point.as_dict()
        record.update(
            {
                "status": self.status,
                "measurements": self.measurements,
                "seconds": round(self.seconds, 3),
                "deck": self.deck,
                "log": self.log,
            }
        )
        # Only a genuinely multi-deck point says so: a single-deck record keeps
        # exactly the shape it had before 'phases' existed.
        if len(self.phases) > 1:
            record["phases"] = [p.as_dict() for p in self.phases]
        if self.missing:
            record["missing_measurements"] = self.missing
        if self.not_measured:
            record["not_measured"] = self.not_measured
        written = {
            name: raw.path.name
            for name, raw in self.raw_files.items()
            if raw.exists()
        }
        if written:
            record["raw_files"] = written
        if self.raw_files_missing:
            record["raw_files_missing"] = self.raw_files_missing
        if self.message:
            record["message"] = self.message
        return record


def parse_measurements(text: str, raw_names: list[str] | tuple[str, ...] = ()) -> dict[str, float]:
    """Extract every measurement from raw ngspice batch output.

    Two independent forms are recognised:

    - ``let``-expression measures, printed by the harness as ``m_<name> =
      <value>`` (bandgap's convention, kept verbatim).
    - raw ``.measure`` results, which ngspice prints automatically in batch
      mode as ``<name> = <value>`` (no ``m_`` prefix). These are only
      searched for by *known* name (``raw_names``, from the testbench
      manifest) rather than a generic ``name = value`` pattern, so an
      unrelated log line (e.g. a echoed ``.param``) can never be mistaken
      for a measurement.
    """
    found: dict[str, float] = {}
    for line in text.splitlines():
        match = _MEAS_LET_RE.match(line)
        if match:
            try:
                found[match.group(1)] = float(match.group(2))
            except ValueError:  # pragma: no cover - regex already constrains this
                continue
    for name in raw_names:
        # Not end-anchored: ngspice appends extra fields after a trig/targ
        # measurement's value on the same line (e.g.
        # "res_tau = 3.8e-09 targ= 2.0e-07 trig= 1.9e-07"), which an
        # end-anchored pattern would silently fail to match.
        pattern = re.compile(
            rf"^\s*{re.escape(name)}\s*=\s*([-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?)",
            re.IGNORECASE | re.MULTILINE,
        )
        match = pattern.search(text)
        if match:
            try:
                found[name] = float(match.group(1))
            except ValueError:  # pragma: no cover - regex already constrains this
                continue
    return found


def run_point(
    tb: Testbench,
    pdk: Pdk,
    point: PvtPoint,
    workdir: Path,
    timeout_s: int = DEFAULT_TIMEOUT_S,
    log_dir: Path | None = None,
) -> PointResult:
    """Simulate one PVT point. Never raises for simulation failure.

    ``workdir`` holds the generated deck (scratch, disposable). ``log_dir``
    -- when given -- is where the raw ngspice output lands as
    ``<corner-id>.log``; that is the ``sim/<slug>/corners/<record-id>/``
    directory from ``sim/README.md``. It defaults to ``workdir`` so a
    throwaway run does not touch the evidence tree.

    When the manifest declares ``raw_files``, ngspice is run from a per-point
    subdirectory ``<workdir>/<corner-id>.d/`` instead of from ``workdir``
    itself, so that two points writing the same ``wrdata`` filename cannot
    overwrite each other under ``-j``. The generated deck stays at
    ``<workdir>/<corner-id>.spice`` (it is passed to ngspice by absolute path),
    so the documented reproduce-by-hand invocation is unchanged.

    A manifest that declares ``phases`` runs **one ngspice invocation per
    phase, per point**, in manifest order, and reduces them into ONE result:
    the measurements merge into one row, the raw files merge into one map, and
    the campaign's ``derive_point()`` runs once over the merged pair. Each
    phase's own files are prefixed with its name -- ``push_ss_125c_3.63v.log``,
    ``jit_ss_125c_3.63v.log`` -- which is the ``[<kind>_]`` corner-id field
    ``sim/README.md`` already ratifies. Phases stop at the first one that fails
    or errors: the record's claim is the whole set, so continuing would only
    produce a point that looks half-measured.
    """
    workdir.mkdir(parents=True, exist_ok=True)
    log_dir = workdir if log_dir is None else log_dir
    log_dir.mkdir(parents=True, exist_ok=True)

    measurements: dict[str, float] = {}
    raw_files: dict[str, RawFile] = {}
    raw_missing: list[str] = []
    missing: list[str] = []
    not_measured: list[str] = []
    runs: list[PhaseRun] = []
    elapsed = 0.0
    failed: PhaseRun | None = None

    for phase in tb.run_phases:
        outcome = _run_phase(tb, phase, pdk, point, workdir, timeout_s, log_dir)
        runs.append(outcome.run)
        elapsed += outcome.run.seconds
        measurements.update(outcome.measurements)
        raw_files.update(outcome.raw_files)
        raw_missing.extend(outcome.raw_missing)
        missing.extend(outcome.missing)
        not_measured.extend(outcome.not_measured)
        if outcome.run.status != "ok":
            failed = outcome.run
            break

    common = {
        "point": point,
        "raw_files": raw_files,
        "raw_files_missing": raw_missing,
        "seconds": elapsed,
        "deck": runs[0].deck,
        "log": runs[0].log,
        "phases": tuple(runs),
    }

    if failed is not None:
        return PointResult(
            status=failed.status,
            measurements=measurements,
            missing=missing,
            not_measured=not_measured,
            message=failed.message,
            **common,
        )

    if tb.derived is not None and tb.derived.measures:
        try:
            measurements.update(
                derive_point_measures(
                    tb.derived, _point_view(tb, point, measurements, raw_files)
                )
            )
        except DerivedError as exc:
            return PointResult(
                status="error",
                measurements=measurements,
                message=str(exc),
                **common,
            )

    return PointResult(
        status="ok",
        measurements=measurements,
        not_measured=[n for n in tb.measure_names if n not in measurements],
        **common,
    )


def _run_phase(
    tb: Testbench,
    phase: Phase,
    pdk: Pdk,
    point: PvtPoint,
    workdir: Path,
    timeout_s: int,
    log_dir: Path,
) -> _PhaseOutcome:
    """One deck, one PVT point: compose, run, parse, capture.

    Everything that used to be the body of :func:`run_point` up to the derived
    reduction. The reduction stays in ``run_point`` because it runs **once**
    over every phase's merged measurements and raw files -- reducing the decks
    together is the whole reason they share a record.
    """
    run_id = phase.run_id(point.corner_id)
    deck_path = workdir / f"{run_id}.spice"
    log_path = log_dir / f"{run_id}.log"
    deck_path.write_text(compose_deck(tb, pdk, point, phase))
    rundir = workdir
    if phase.raw_files:
        rundir = workdir / f"{run_id}.d"
        rundir.mkdir(parents=True, exist_ok=True)

    started = time.monotonic()
    try:
        proc = subprocess.run(
            [NGSPICE, "-b", str(deck_path)],
            capture_output=True,
            text=True,
            timeout=timeout_s,
            cwd=rundir,
            check=False,
        )
        output = proc.stdout + "\n" + proc.stderr
        returncode = proc.returncode
    except FileNotFoundError as exc:
        raise NgspiceMissing(str(exc)) from exc
    except subprocess.TimeoutExpired:
        elapsed = time.monotonic() - started
        log_path.write_text(f"TIMEOUT after {timeout_s}s\n")
        # A killed deck never reached its `wrdata` line, so every declared raw
        # file is reported absent rather than left unexplained.
        timed_out_raw = capture_raw_files(tb, point, rundir, log_dir, phase)
        return _PhaseOutcome(
            run=PhaseRun(
                name=phase.name,
                status="error",
                deck=deck_path.name,
                log=log_path.name,
                seconds=elapsed,
                message=f"ngspice timed out after {timeout_s}s",
            ),
            raw_files=timed_out_raw,
            raw_missing=[n for n, raw in timed_out_raw.items() if not raw.exists()],
        )
    elapsed = time.monotonic() - started
    log_path.write_text(output)

    # Capture what the deck wrote BEFORE anything else looks at this point: a
    # retained raw file is evidence, and it has to be banked whether the point
    # went on to pass, fail a required measurement, or break its reduction.
    raw_files = capture_raw_files(tb, point, rundir, log_dir, phase)
    raw_missing = [name for name, raw in raw_files.items() if not raw.exists()]

    measurements = parse_measurements(output, phase.raw_measures.keys())
    # Only *required* measurements can fail a point. An absent optional
    # measurement is the campaign's pass condition ("this must never assert"),
    # and treating it as a failure used to discard every measurement the same
    # point took successfully.
    missing = [n for n in phase.required_measure_names if n not in measurements]

    if missing:
        errors = "; ".join(_ERROR_RE.findall(output)[:3])
        first_error = next(
            (line.strip() for line in output.splitlines() if _ERROR_RE.match(line)), ""
        )
        return _PhaseOutcome(
            run=PhaseRun(
                name=phase.name,
                status="failed",
                deck=deck_path.name,
                log=log_path.name,
                seconds=elapsed,
                message=first_error
                or errors
                or f"ngspice exit {returncode}, no measurements parsed",
            ),
            measurements=measurements,
            missing=missing,
            not_measured=[
                name for name in phase.measure_names
                if tb.is_optional(name) and name not in measurements
            ],
            raw_files=raw_files,
            raw_missing=raw_missing,
        )

    return _PhaseOutcome(
        run=PhaseRun(
            name=phase.name,
            status="ok",
            deck=deck_path.name,
            log=log_path.name,
            seconds=elapsed,
        ),
        measurements=measurements,
        # Carried even on success so that a *later* phase's failure still
        # reports what this one legitimately did not measure.
        not_measured=[
            name for name in phase.measure_names
            if tb.is_optional(name) and name not in measurements
        ],
        raw_files=raw_files,
        raw_missing=raw_missing,
    )


def capture_raw_files(
    tb: Testbench, point: PvtPoint, rundir: Path, log_dir: Path,
    phase: Phase | None = None,
) -> dict[str, RawFile]:
    """Resolve the manifest's ``raw_files`` against what this point wrote.

    Runs immediately after ngspice returns, so the reduction sees the file
    while it is still on disk and a ``retain`` file is banked as evidence
    before anything can go wrong downstream.

    ``phase`` scopes this to one deck of a phased manifest -- only that deck's
    declared files, and its own ``[<kind>_]<corner-id>`` stem for a retained
    copy. Omitted (the single-deck case) it is every declared file, under the
    bare ``<corner-id>`` stem, exactly as before.

    A ``retain`` file is copied out of the point's scratch directory into
    ``log_dir`` (``corners/<record-id>/``) as ``<corner-id>-<name>``, alongside
    the point's own ``<corner-id>.log``, and the returned :class:`RawFile`
    points at that retained copy -- a reduction and a later reader then read
    the same bytes. Everything else stays in the git-ignored scratch tree,
    where it is still readable by ``derive_point`` and, because nothing deletes
    the work directory, by ``derive_tables`` after every point has run.

    A declared file the deck never wrote yields a :class:`RawFile` whose
    ``exists()`` is ``False`` rather than an exception.
    """
    specs = tb.raw_files if phase is None else phase.raw_files
    run_id = point.corner_id if phase is None else phase.run_id(point.corner_id)
    captured: dict[str, RawFile] = {}
    for spec in specs:
        source = rundir / spec.name
        path = source
        if spec.retain and source.is_file():
            path = log_dir / f"{run_id}-{spec.name}"
            path.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, path)
        captured[spec.name] = RawFile(
            name=spec.name, path=path, columns=spec.columns
        )
    return captured


def _point_view(
    tb: Testbench,
    point: PvtPoint,
    measurements: dict[str, float],
    raw_files: dict[str, RawFile] | None = None,
) -> PointView:
    """The read-only view handed to a campaign's ``derive_point()``."""
    params = {str(k): str(v) for k, v in tb.params.items()}
    params.update(point.params)
    return PointView(
        corner=point.corner.name,
        corner_id=point.corner_id,
        temp_c=point.temp_c,
        vdd=point.vdd,
        axes=point.axes,
        params=params,
        measurements=dict(measurements),
        raw_files=dict(raw_files or {}),
    )


def run_grid(
    tb: Testbench,
    pdk: Pdk,
    points: list[PvtPoint],
    workdir: Path,
    jobs: int = 1,
    timeout_s: int = DEFAULT_TIMEOUT_S,
    on_result=None,
    log_dir: Path | None = None,
) -> list[PointResult]:
    """Run every PVT point; results come back in grid order regardless of jobs."""
    results: list[PointResult | None] = [None] * len(points)

    def _one(index_point):
        index, point = index_point
        result = run_point(tb, pdk, point, workdir, timeout_s=timeout_s, log_dir=log_dir)
        results[index] = result
        if on_result is not None:
            on_result(result)
        return result

    if jobs <= 1:
        for item in enumerate(points):
            _one(item)
    else:
        with ThreadPoolExecutor(max_workers=jobs) as pool:
            list(pool.map(_one, enumerate(points)))

    return [r for r in results if r is not None]
