#!/usr/bin/env python3
"""Unit tests for ``design/lib/check-io-list-coverage.sh`` (issue #237).

    python3 -m unittest discover -s design/tests -v

The check grades the Chipalooza proposal's I/O list -- #237's AC4 deliverable
whose source of truth is not a document but ``design/netlist/pll_top.spice``,
the committed export of ``design/pll_top.sch``.  ``sim/lib/pll_top_dut.sh``
already refuses to run a closed-loop campaign whose netlist port list does not
match its own ``CLOOP_PORTS``, name for name and in order; the document written
to be emailed verbatim to an outside reader had no equivalent guard, and its
reader cannot re-run anything to find out.

The drift is historical, not hypothetical: PR #418 added ``LDT0``-``LDT3`` as
real top-level ports, issue #441 found section 2.2's pad table still had no row
for them three days later ("the proposal described a part that could not be
configured into its own ratified spec", DR-015), and DR-015's own closing
sentence handed the bench-test-plan half of the same fix to "future harness
integration work" that never happened -- so section 4 still named neither the
trim pins nor the four bias-reference currents when this check was written.

Every test builds a throwaway tree whose answer is known and runs the real
script in it, because a check that only ever runs where it passes proves
nothing about what it would have caught.  No PDK, no ngspice, no xschem -- the
script reads one committed netlist and one committed Markdown file.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

DESIGN_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = DESIGN_DIR.parent
CHECK = DESIGN_DIR / "lib" / "check-io-list-coverage.sh"

NETLIST = "design/netlist/pll_top.spice"
PROPOSAL = "docs/chipalooza/challenge-5-proposal.md"

#: A miniature of the real 36-port export, keeping every shape the real one
#: has: a bus the document writes as a range, a bus it writes with an
#: ellipsis, single-pin signals, and rails.
PORTS = (
    "REF",
    "B0",
    "B1",
    "B2",
    "LDT0",
    "LDT1",
    "LDT2",
    "LDT3",
    "IBN",
    "ICP",
    "CLK",
    "LOCK",
    "VDD",
    "VSS",
)

#: (Signal(s) cell, Count-used cell) -- the two columns the check reads.
PAD_ROWS = (
    ("`VDD`, `VSS`", "— (rail)"),
    ("`REF`", "1 of 24"),
    ("`B0`, `B1`, `B2`", "3 of 24"),
    ("`LDT0`…`LDT3`", "4 of 24"),
    ("`IBN`, `ICP`", "2 requested vs. 2 offered"),
    ("`CLK`", "1 of 4"),
    ("`LOCK`", "1 of 12"),
)

#: The bench plan, as a list of steps.  Between them these name every port.
BENCH_STEPS = (
    "**Bring-up.** Power `VDD` with `VSS` grounded; supply `IBN` and `ICP`.",
    "**Open-loop.** Sweep `B0..B2` and measure `CLK`.",
    "**Trim.** Program `LDT3:LDT0` per the trim-code rule.",
    "**Lock.** Apply `REF` and observe `LOCK`.",
)


def _netlist(ports=PORTS, subckt=".subckt pll_top") -> str:
    """The export, wrapped onto a `+` continuation line the way ngspice does."""
    head, tail = ports[:8], ports[8:]
    lines = [
        "* gf180-pll :: pll_top -- generated by design/netlist.sh from pll_top.sch",
        "** sch_path: design/pll_top.sch",
        "%s %s" % (subckt, " ".join(head)),
    ]
    if tail:
        lines.append("+ %s" % " ".join(tail))
    lines += ["*.ipin %s" % ports[0], ".ends pll_top"]
    return "\n".join(lines) + "\n"


def _proposal(
    pad_rows=PAD_ROWS,
    bench_steps=BENCH_STEPS,
    quoted=None,
    pad_heading="### 2.2 Pad table, mapped to the Challenge #5 slot budget",
    bench_heading="## 4. Bench test plan",
    pad_header="| Signal(s) | Dir | Challenge slot | Count used | Notes |",
) -> str:
    if quoted is None:
        quoted = " ".join(PORTS)
    lines = [
        "# Chipalooza Challenge #5 — integer-N PLL proposal",
        "",
        "## 2. I/O list, including test ports",
        "",
        pad_heading,
        "",
        "`design/pll_top.sch`'s exported port list",
        "(`design/netlist/pll_top.spice`, `.subckt pll_top %s`) is the port" % quoted,
        "list this table maps, unedited.",
        "",
        pad_header,
        "|---|---|---|---|---|",
    ]
    for signal, count in pad_rows:
        lines.append("| %s | in | a slot | %s | a note |" % (signal, count))
    lines += [
        "",
        "## 3. Functional description",
        "",
        "Prose naming no pins.",
        "",
        bench_heading,
        "",
        "All measurements below use only the pads in §2.2.",
        "",
    ]
    for n, step in enumerate(bench_steps, start=1):
        lines.append("%d. %s" % (n, step))
    lines += ["", "## 5. Target specification", "", "Text after."]
    return "\n".join(lines) + "\n"


class _Tree:
    """A throwaway repo tree with the real check installed at design/lib/."""

    def __init__(self, root: Path):
        self.root = root
        (root / "design" / "lib").mkdir(parents=True)
        shutil.copy2(CHECK, root / "design" / "lib" / CHECK.name)
        self.write(NETLIST, _netlist())
        self.write(PROPOSAL, _proposal())

    def write(self, rel: str, text: str) -> None:
        path = self.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def run(self) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["bash", str(self.root / "design" / "lib" / CHECK.name)],
            capture_output=True,
            text=True,
        )


class _TreeTest(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.tree = _Tree(Path(self._tmp.name))
        self.addCleanup(self._tmp.cleanup)

    def assertPasses(self) -> subprocess.CompletedProcess:
        result = self.tree.run()
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        return result

    def assertFails(self, *needles: str) -> subprocess.CompletedProcess:
        result = self.tree.run()
        self.assertEqual(result.returncode, 1, msg=result.stdout + result.stderr)
        for needle in needles:
            self.assertIn(needle, result.stderr)
        return result


class TestCoverageRule(_TreeTest):
    def test_a_fully_mapped_port_list_passes(self):
        self.assertPasses()

    def test_the_real_441_drift_shape_is_caught(self):
        """The exact regression: ports added to design/, pad table untouched.

        This is the proposal as it stood between PR #418 and issue #441 --
        `LDT0`-`LDT3` real top-level ports of `pll_top`, with no pad row.
        """
        self.tree.write(
            PROPOSAL,
            _proposal(
                pad_rows=tuple(r for r in PAD_ROWS if "LDT" not in r[0]),
                bench_steps=BENCH_STEPS,
            ),
        )
        self.assertFails(
            "port 'LDT0'",
            "has no row in docs/chipalooza/challenge-5-proposal.md section 2.2",
        )

    def test_every_missing_port_is_reported_not_just_the_first(self):
        self.tree.write(
            PROPOSAL,
            _proposal(pad_rows=tuple(r for r in PAD_ROWS if "LDT" not in r[0])),
        )
        result = self.tree.run()
        for port in ("LDT0", "LDT1", "LDT2", "LDT3"):
            self.assertIn("port %r" % port, result.stderr)

    def test_a_range_covers_its_interior_not_only_its_endpoints(self):
        """`B0`, `B1`, `B2` written as `B0..B2` still maps B1."""
        self.tree.write(
            PROPOSAL,
            _proposal(
                pad_rows=tuple(
                    ("`B0..B2`", c) if s.startswith("`B0`") else (s, c)
                    for s, c in PAD_ROWS
                )
            ),
        )
        self.assertPasses()

    def test_a_short_form_range_covers_its_interior(self):
        """`LDT0..3` -- the form section 4 uses -- expands on the prefix."""
        self.tree.write(
            PROPOSAL,
            _proposal(
                pad_rows=tuple(
                    ("`LDT0..3`", c) if "LDT" in s else (s, c) for s, c in PAD_ROWS
                )
            ),
        )
        self.assertPasses()

    def test_a_descending_bus_range_covers_its_interior(self):
        """`LDT3:LDT0` is the spec's own spelling of the same four bits."""
        self.tree.write(
            PROPOSAL,
            _proposal(
                pad_rows=tuple(
                    ("`LDT3:LDT0`", c) if "LDT" in s else (s, c) for s, c in PAD_ROWS
                )
            ),
        )
        self.assertPasses()


class TestOrphanSignalRule(_TreeTest):
    def test_a_pad_row_naming_a_nonexistent_pin_fails(self):
        """Catches a pin renamed or removed in design/ but left in the table."""
        self.tree.write(
            PROPOSAL, _proposal(pad_rows=PAD_ROWS + (("`SPI_CS`", "1 of 24"),))
        )
        self.assertFails("names 'SPI_CS', which is not a port")

    def test_a_renamed_pin_fails_in_both_directions(self):
        renamed = tuple("REFCLK" if p == "REF" else p for p in PORTS)
        self.tree.write(NETLIST, _netlist(renamed))
        self.tree.write(PROPOSAL, _proposal(quoted=" ".join(renamed)))
        self.assertFails("port 'REFCLK'", "names 'REF', which is not a port")


class TestQuotedPortListRule(_TreeTest):
    def test_a_stale_quoted_list_fails(self):
        self.tree.write(
            PROPOSAL, _proposal(quoted=" ".join(p for p in PORTS if p != "LDT3"))
        )
        self.assertFails("does not match design/netlist/pll_top.spice")

    def test_a_reordered_quoted_list_fails(self):
        """The order is load-bearing: a positional instance line reads it."""
        swapped = list(PORTS)
        swapped[0], swapped[1] = swapped[1], swapped[0]
        self.tree.write(PROPOSAL, _proposal(quoted=" ".join(swapped)))
        self.assertFails("does not match design/netlist/pll_top.spice")

    def test_a_quoted_continuation_marker_is_allowed(self):
        """The netlist wraps and the document quotes the wrap, `+` and all."""
        with_plus = list(PORTS)
        with_plus.insert(8, "+")
        self.tree.write(PROPOSAL, _proposal(quoted=" ".join(with_plus)))
        self.assertPasses()

    def test_an_unquoted_port_list_fails(self):
        text = _proposal().replace(
            "(`design/netlist/pll_top.spice`, `.subckt pll_top %s`) is the port"
            % " ".join(PORTS),
            "(`design/netlist/pll_top.spice`) is the port",
        )
        self.tree.write(PROPOSAL, text)
        self.assertFails("does not quote the '.subckt pll_top' line anywhere")


class TestPerRowCountRule(_TreeTest):
    def test_a_stale_row_count_fails(self):
        """What went stale first in #441: the count beside the changed row."""
        self.tree.write(
            PROPOSAL,
            _proposal(
                pad_rows=tuple(
                    (s, "3 of 24") if "LDT" in s else (s, c) for s, c in PAD_ROWS
                )
            ),
        )
        self.assertFails("states '3 of 24' but names 4 signal(s)")

    def test_a_requested_vs_offered_count_is_graded_too(self):
        self.tree.write(
            PROPOSAL,
            _proposal(
                pad_rows=tuple(
                    (s, "4 requested vs. 2 offered") if s == "`IBN`, `ICP`" else (s, c)
                    for s, c in PAD_ROWS
                )
            ),
        )
        self.assertFails("but names 2 signal(s)")

    def test_a_rail_row_states_no_count_and_is_exempt(self):
        """"— (rail)" is not a number and must not be read as one."""
        self.assertPasses()

    def test_an_emphasised_count_is_still_graded(self):
        self.tree.write(
            PROPOSAL,
            _proposal(
                pad_rows=tuple(
                    (s, "**2** of 24") if "LDT" in s else (s, c) for s, c in PAD_ROWS
                )
            ),
        )
        self.assertFails("but names 4 signal(s)")


class TestBenchPlanRule(_TreeTest):
    def test_a_pin_the_bench_plan_never_names_fails(self):
        """The finding this rule was written on, in miniature.

        Section 4 named neither the lock-detector trim nor the four bias
        currents.  Both are load-bearing: without the bias references the
        charge pump passes no current, and `spec/pll.md` says outright that a
        part left untrimmed is outside the specification the plan's
        lock-detector step compares it against.
        """
        self.tree.write(
            PROPOSAL,
            _proposal(
                bench_steps=tuple(s for s in BENCH_STEPS if "`LDT3:LDT0`" not in s)
            ),
        )
        self.assertFails(
            "port 'LDT0' is never named in docs/chipalooza/challenge-5-proposal.md"
            " section 4"
        )

    def test_a_bias_pin_the_bench_plan_never_names_fails(self):
        self.tree.write(
            PROPOSAL,
            _proposal(
                bench_steps=tuple(
                    s.replace("; supply `IBN` and `ICP`", "") for s in BENCH_STEPS
                )
            ),
        )
        self.assertFails("port 'IBN' is never named", "port 'ICP' is never named")

    def test_a_pad_table_mention_does_not_satisfy_the_bench_rule(self):
        """The two sections are graded separately, on purpose.

        `LDT0`-`LDT3` were in the pad table for four days before this check
        existed while section 4 still ignored them; a rule that accepted a
        mention anywhere in the document would have reported that tree clean.
        """
        self.tree.write(
            PROPOSAL,
            _proposal(
                bench_steps=tuple(s for s in BENCH_STEPS if "`LDT3:LDT0`" not in s)
            ),
        )
        self.assertFails("section 4")


class TestSelfDefence(_TreeTest):
    def test_a_missing_netlist_fails(self):
        (self.tree.root / NETLIST).unlink()
        self.assertFails("%s does not exist" % NETLIST)

    def test_a_missing_proposal_fails(self):
        (self.tree.root / PROPOSAL).unlink()
        self.assertFails("%s does not exist" % PROPOSAL)

    def test_a_netlist_without_the_subckt_line_fails(self):
        self.tree.write(NETLIST, _netlist(subckt=".subckt pll_toplevel"))
        self.assertFails("has no '.subckt pll_top' line")

    def test_a_truncated_port_list_fails_rather_than_reading_clean(self):
        """A `+` continuation the parser dropped must not look like a pass.

        The first draft of this check did exactly that: it read the `.subckt`
        line and stopped at the newline, so pll_top's real 36 ports parsed as
        27 and the nine on the continuation line went ungraded.
        """
        self.tree.write(NETLIST, _netlist(PORTS[:6]))
        self.assertFails("too few to be real")

    def test_a_renamed_pad_section_fails(self):
        self.tree.write(PROPOSAL, _proposal(pad_heading="### 2.2b Pad table"))
        self.assertFails("has no '### 2.2' section")

    def test_a_renumbered_bench_section_fails(self):
        self.tree.write(PROPOSAL, _proposal(bench_heading="## 4A. Bench test plan"))
        self.assertFails("has no '## 4.' section")

    def test_a_pad_table_that_stops_parsing_fails(self):
        self.tree.write(PROPOSAL, _proposal(pad_rows=PAD_ROWS[:2]))
        self.assertFails("too few to be real")

    def test_a_missing_signal_column_fails(self):
        self.tree.write(
            PROPOSAL,
            _proposal(pad_header="| Pin | Dir | Challenge slot | Count used | Notes |"),
        )
        self.assertFails("has no 'signal(s)' column")

    def test_a_missing_count_column_fails(self):
        self.tree.write(
            PROPOSAL,
            _proposal(pad_header="| Signal(s) | Dir | Challenge slot | Slots | Notes |"),
        )
        self.assertFails("has no 'count used' column")


class TestFalsePositives(_TreeTest):
    def test_a_path_in_backticks_is_not_a_pin(self):
        self.tree.write(
            PROPOSAL,
            _proposal(
                bench_steps=BENCH_STEPS
                + ("Compare against `spec/pll.md#kvco` and `sim/lock-time`.",)
            ),
        )
        self.assertPasses()

    def test_a_lowercase_net_name_is_not_a_pin(self):
        self.tree.write(
            PROPOSAL,
            _proposal(
                pad_rows=tuple(
                    (s, c) if s != "`VDD`, `VSS`" else ("`VDD`, `VSS`", c)
                    for s, c in PAD_ROWS
                ),
                bench_steps=BENCH_STEPS + ("`vdd_ref` is this domain's name.",),
            ),
        )
        self.assertPasses()

    def test_a_decision_record_id_is_not_a_range(self):
        self.tree.write(
            PROPOSAL, _proposal(bench_steps=BENCH_STEPS + ("Per DR-014: trim once.",))
        )
        self.assertPasses()


class TestTheRealTree(unittest.TestCase):
    def test_the_committed_tree_passes(self):
        result = subprocess.run(
            ["bash", str(CHECK)], capture_output=True, text=True, cwd=str(REPO_ROOT)
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertIn("are mapped in", result.stdout)

    def test_the_real_port_list_is_the_36_the_sim_harness_pins(self):
        """Cross-checks the parser against sim/lib/pll_top_dut.sh's CLOOP_PORTS.

        That list is the other place in this repository that must agree with
        the export, and it aborts a closed-loop run when it does not.  If this
        check's parser ever disagrees with it, one of the two is wrong about
        what `pll_top`'s ports are.
        """
        lib = (REPO_ROOT / "sim" / "lib" / "pll_top_dut.sh").read_text(encoding="utf-8")
        block = lib.split("CLOOP_PORTS=(", 1)[1].split(")", 1)[0]
        cloop = block.split()
        netlist = (REPO_ROOT / NETLIST).read_text(encoding="utf-8")
        declared = netlist.split(".subckt pll_top", 1)[1].splitlines()
        ports = declared[0].split()
        for line in declared[1:]:
            if not line.startswith("+"):
                break
            ports += line[1:].split()
        self.assertEqual(ports, cloop)


if __name__ == "__main__":
    unittest.main()
