#!/usr/bin/env python3
"""Unit tests for ``design/lib/check-port-connectivity.sh`` (issue #515).

    python3 -m unittest discover -s design/tests -v

Issue #515: `design/pll_top.sch` placed the `LDT3` trim label three grid rows
off the `XLD` lock-detector instance's actual `LDT3` pin, so the exported
netlist wired `.subckt pll_top`'s eighth `XLD` argument to `net1` -- an
xschem auto-named net with exactly one connection -- instead of to the
`LDT3` port declared two lines above it. `design/netlist.sh --check` cannot
catch this shape of defect: the export was internally consistent with the
broken schematic, so there was nothing to diff against. This check grades the
netlist against itself instead -- every declared port of a committed
netlist's own top-level subcircuit must be connected somewhere in that same
subcircuit's body, and no auto-named `net<N>` anywhere in the file may carry
exactly one connection.

Every test builds a throwaway tree with a miniature netlist and runs the real
script in it, because a check that only ever runs where it passes proves
nothing about what it would have caught. No PDK, no ngspice, no xschem -- the
script reads committed `.spice` text.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

DESIGN_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = DESIGN_DIR.parent
CHECK = DESIGN_DIR / "lib" / "check-port-connectivity.sh"


def _pll_top_netlist(ldt3_wired: bool = True) -> str:
    """A miniature `pll_top.spice`-shaped export.

    Mirrors the real file's shape closely enough to exercise both rules: a
    `.subckt pll_top` with a wrapped port list, one instance line per pin
    (some of them multi-argument, the way `XLD` really is), and a second
    `.subckt` further down (`lock_detector`) the way the real committed
    export inlines its whole hierarchy -- so the check has something to
    prove it is NOT recursing into when it grades `pll_top`'s own ports.
    """
    ldt3_arg = "LDT3" if ldt3_wired else "net1"
    lines = [
        "* gf180-pll :: pll_top -- generated by design/netlist.sh from pll_top.sch",
        "** sch_path: design/pll_top.sch",
        ".subckt pll_top REF B0 LDT0 LDT1 LDT2 LDT3 VDD",
        "+ VSS",
        "*.ipin REF",
        "XLD UP DN LOCK VWIN LDT0 LDT1 LDT2 %s VDD VSS lock_detector" % ldt3_arg,
        "XREF REF B0 UP VDD VSS pfd_cp",
        ".ends",
        "",
        ".subckt lock_detector UP DN LOCK VWIN LDT0 LDT1 LDT2 LDT3 VDD VSS",
        "XM1 UP DN VDD VDD pfet_03v3 L=0.5u W=2u ad='1' nf=1",
        ".ends",
        "",
        ".subckt pfd_cp REF B0 UP VDD VSS",
        "XM2 REF B0 UP VDD nfet_03v3 L=0.5u W=2u",
        ".ends",
    ]
    return "\n".join(lines) + "\n"


class _Tree:
    """A throwaway repo tree with the real check installed at design/lib/."""

    def __init__(self, root: Path):
        self.root = root
        (root / "design" / "lib").mkdir(parents=True)
        (root / "design" / "netlist").mkdir(parents=True)
        shutil.copy2(CHECK, root / "design" / "lib" / CHECK.name)

    def write(self, rel: str, text: str) -> None:
        path = self.root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def run(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["bash", str(self.root / "design" / "lib" / CHECK.name), *args],
            capture_output=True,
            text=True,
            cwd=self.root,
        )


class _TreeTest(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.tree = _Tree(Path(self._tmp.name))
        self.addCleanup(self._tmp.cleanup)

    def assertPasses(self, *args: str) -> subprocess.CompletedProcess:
        result = self.tree.run(*args)
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        return result

    def assertFails(self, *needles: str) -> subprocess.CompletedProcess:
        result = self.tree.run()
        self.assertEqual(result.returncode, 1, msg=result.stdout + result.stderr)
        for needle in needles:
            self.assertIn(needle, result.stderr)
        return result


class TestPortConnectivity(_TreeTest):
    def test_a_fully_wired_netlist_passes(self):
        self.tree.write("design/netlist/pll_top.spice", _pll_top_netlist())
        self.assertPasses()

    def test_the_real_515_regression_is_caught(self):
        """The exact regression: LDT3 declared, wired to net1 instead."""
        self.tree.write(
            "design/netlist/pll_top.spice", _pll_top_netlist(ldt3_wired=False)
        )
        self.assertFails(
            "declares port 'LDT3'",
            "no instance line inside that subcircuit's own body connects",
            "auto-named net 'net1' with exactly 1 connection",
        )

    def test_an_auto_named_net_with_two_connections_is_fine(self):
        """A net xschem left unlabeled is not itself the defect.

        `net1` appearing twice means two real pins share it -- an ordinary
        unlabeled internal wire, not a floating stub. Only a single
        connection is the signature this check grades.
        """
        netlist = _pll_top_netlist().replace(
            "XREF REF B0 UP VDD VSS pfd_cp",
            "XREF REF B0 net9 VDD VSS pfd_cp\n"
            "XREF2 net9 B0 UP VDD VSS pfd_cp",
        )
        self.tree.write("design/netlist/pll_top.spice", netlist)
        self.assertPasses()

    def test_a_singly_connected_auto_named_net_fails_even_off_a_port(self):
        """The single-connection rule catches a floating INTERNAL node too.

        Renaming `net9` above to have only one connection must fail even
        though `net9` is not a declared port at all -- rule 2 does not need
        rule 1's port list to catch this shape of defect.
        """
        netlist = _pll_top_netlist().replace(
            "XREF REF B0 UP VDD VSS pfd_cp",
            "XREF REF B0 net9 VDD VSS pfd_cp",
        )
        self.tree.write("design/netlist/pll_top.spice", netlist)
        self.assertFails("auto-named net 'net9' with exactly 1 connection")

    def test_missing_file_fails(self):
        result = self.tree.run("design/netlist/does-not-exist.spice")
        self.assertEqual(result.returncode, 1, msg=result.stdout + result.stderr)
        self.assertIn("does not exist", result.stderr)

    def test_no_subckt_at_all_fails(self):
        self.tree.write("design/netlist/pll_top.spice", "* empty file\n")
        self.assertFails("has no '.subckt' block at all")

    def test_default_glob_checks_every_netlist_in_the_tree(self):
        """No arguments: every design/netlist/*.spice file is checked."""
        self.tree.write("design/netlist/pll_top.spice", _pll_top_netlist())
        self.tree.write(
            "design/netlist/lock_detector.spice",
            _pll_top_netlist(ldt3_wired=False).split(".ends", 1)[0] + ".ends\n",
        )
        result = self.tree.run()
        self.assertEqual(result.returncode, 1, msg=result.stdout + result.stderr)
        self.assertIn("lock_detector.spice", result.stderr)

    def test_default_glob_is_resolved_against_repo_root_not_cwd(self):
        """Running from elsewhere must not silently check zero files."""
        self.tree.write("design/netlist/pll_top.spice", _pll_top_netlist())
        result = subprocess.run(
            ["bash", str(self.tree.root / "design" / "lib" / CHECK.name)],
            capture_output=True,
            text=True,
            cwd=str(Path(tempfile.gettempdir())),
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        self.assertIn("1 netlist(s) checked", result.stdout)


if __name__ == "__main__":
    unittest.main()
