"""``vco_bias.sch``'s V-to-I core: the dozen-odd transistors ``bias_resistors.py``
named as issue #293's own remaining scope (``MP1``/``MP2``/``MN1``/``MN2``/
``MSU1``-``MSU3``/``MPR``/``MD1``/``MD2``/``MOFF``/``MVI``/``MSUM``).

WHAT THIS CIRCUIT DOES (read directly off ``design/vco_bias.sch`` /
``design/netlist/vco.spice`` -- see ``devices.py``'s own V-to-I section for
the per-device table)
--------------------------------------------------------------------------
Four cooperating pieces, all summed into one output node (``VBP0``):

* **Constant-gm reference**: ``MP1``/``MN1`` (a diode-connected branch,
  node ``NA``) sets the gate of ``MN2``, whose source is degenerated by
  ``RCG`` (through node ``NC``) against ``MP2``'s own diode-connected drain
  (node ``VBPC``) -- the classic beta-multiplier bias cell.
* **Startup**: ``MSU1`` (gate tied permanently to ``GND_VCO`` -- an
  always-on weak pull-up) and ``MSU2`` (gate driven by ``NA``) form a
  detector on node ``NSU``; ``MSU3`` uses ``NSU`` to kick ``VBPC`` low at
  power-up so the constant-gm loop cannot get stuck at its degenerate
  all-zero-current solution.
* **2*Vgs stacked reference**: ``MPR`` (gate ``VBPC``, i.e. mirrored from
  the constant-gm core) stacks over two diode-connected nfets ``MD1``/
  ``MD2`` (node ``NMD`` between them) to produce a fixed gate bias
  ``VFIX`` for the two branches below.
* **Offset + source-degenerated V-to-I + summing node**: ``MOFF`` (gate
  ``VFIX``, degenerated by ``ROFF`` through node ``NOFF``) sets a fixed
  offset current; ``MVI`` (gate ``VCTRL``, the block's own external
  control-voltage input, degenerated by ``RDEG`` through node ``NVI``) is
  the actual V-to-I converter. Both drains land on ``VBP0``, which
  ``MSUM`` (diode-connected, ``nf=4``) mirrors into a PMOS bias node --
  ``VBP0`` is exactly the net ``mirror.py``'s cascade A already consumes as
  ``devices.CASCADE_A.always_on.gate_net``.

WHY THIS IS ITS OWN BLOCK, NOT MERGED WITH ``bias_resistors.py``
------------------------------------------------------------------
``RCG``/``ROFF``/``RDEG`` (the three ``ppolyf_u_3k`` poly resistors this
core's ``NC``/``NOFF``/``NVI`` nodes connect to) are already drawn, DRC-clean
and standalone, by ``bias_resistors.py``. This module draws every
*transistor* of the V-to-I core as its own standalone, DRC-clean block and
exposes ``NC``/``NOFF``/``NVI`` as Metal1/Metal2 boundary pins **using the
exact same net names** ``bias_resistors.py`` already uses for its own
``top_net`` pins -- so wiring the two blocks together (dropping both into
one shared guard ring, and running one combined DRC pass) is a
well-defined, mechanical follow-up rather than a re-derivation. That
follow-up, plus the identical merge with ``ring.py``/``mirror.py``/
``buffer.py``, has since landed as ``block.py`` -- and it *was* mechanical:
it adds no device geometry at all, only the routes between the pins these
five generators already agreed on, plus one block-level guard ring.
See ``bias_resistors.py``'s module docstring for the same call made for the
resistor trio.

WHY THIS BLOCK USES THE SAME METAL2-MESH ROUTING AS ``mirror.py``
--------------------------------------------------------------------
Unlike ``ring.py``'s block (a simple 5-stage chain) or ``buffer.py``'s
(three independent inverters), this circuit's internal nodes fan out across
more than two devices each, and several (``VBPC``, ``NSU``, ``VFIX``,
``VBP0``) are needed from **both** the NMOS and PMOS rows -- e.g. ``VBPC``
is ``MP1``'s gate, ``MP2``'s diode-connected drain/gate, ``MPR``'s gate
(all PMOS row) *and* ``MSU3``'s drain (NMOS row). That is exactly the
"mesh, not a chain" topology ``mirror.py``'s module docstring names as the
reason for Metal2 tracks -- so this module reuses that exact construction
(one Metal1 escape per device terminal, up/down to a Metal2 track in the
channel between the two rows; nets needed from both rows get a "lo" track
reachable only from the NMOS row and a "hi" track reachable only from the
PMOS row, tied together by one Metal1 link column, per ``mirror.py``'s own
"THE CHANNEL IS SPLIT INTO TWO TRACK GROUPS" rationale) rather than
re-deriving a second routing scheme. Every device here is an ordinary
single- or multi-finger MOSFET (no common-centroid array), so the
cascade-specific code in ``mirror.py`` (``draw_cc_array``,
``check_common_centroid``) has no counterpart here.

``MSUM`` is the one multi-finger device (``nf=4``); its four fingers are
drawn side by side and bused together on all three terminals (source,
drain, gate) as one merged Metal1 rectangle each -- simpler than
``mirror.py``'s interdigitated bus (no second leg to keep separate, so no
second gate bus is needed).

THE ONE DEVICE THAT IS NOT MESH-ROUTED: ``MSU1``'s GATE
------------------------------------------------------------
``MSU1`` (in the PMOS row) has its gate tied permanently to ``GND_VCO`` --
an always-on weak pull-up, not a mesh net. Routing it through the general
escape/track mechanism would need a "GND_VCO" track plus a separate anchor
wire all the way down to the substrate ring, crossing the entire NMOS row's
height. Instead, ``MSU1`` is placed **last** (rightmost) in the PMOS row
(``devices.VTOI_PMOS_ROW``'s own ordering, and its own comment), so nothing
else in either row sits further right, and its gate pad is tied with a
single horizontal Metal1 run at the gate's own height straight out to the
guard ring's right-hand band (which the same ``GND_VCO`` net already ties
via ``primitives.guard_ring()``) -- entirely within the PMOS row's own
vertical span, never descending into the channel/NMOS-row region at all.
``devices.py``'s own ``_net_rows()``-equivalent here excludes any
gate/S/D terminal literally equal to ``VDD_VCO``/``GND_VCO`` from mesh
routing (see ``_net_rows()`` below), so this device's gate is the only one
that needs the bespoke wire rather than an ordinary rail_stub -- every
other rail-tied terminal in this block is a source/drain pad, which
``rail_stub()`` already handles.

EVERY PMOS-ROW BOTTOM/GATE ESCAPE HOPS OVER ``tap_band_bottom`` (issue #376)
------------------------------------------------------------------------
The PMOS row is *top*-aligned (``_y_bottom()``'s own pfet convention: every
item's own top edge is ``plan.pmos_top``, so a shorter device's own body
sits higher, not lower) specifically so ``MSU1``'s own ``l=20 um`` channel
-- the tallest thing in the row -- can reach all the way down to
``plan.pmos_bottom`` without every *other* device's own pads needing to
move. But every PMOS-row device's own **bottom** (source) pad still has to
reach the inter-row channel below, and ``plan.tap_band_bottom`` (the
``VDD_VCO`` n-well tap band ``build()`` draws along the row's own bottom
edge, spanning the *entire* row width) sits directly in that path for
every one of them, not just ``MSU1``. A plain ``escape()`` column -- a
single Metal1 wire straight down to the channel, what every other
mesh-routed net in this block uses -- runs directly through that band's own
drawn Metal1, merging the escaping net into ``VDD_VCO``. Root-caused by
direct ``klayout.db`` connectivity probing (not assumed): all five of this
row's own bottom nets (``NA``, ``VBPC``, ``VFIX``, ``VBP0``, ``NSU``) showed
this identical merge before ``_pmos_row_escape()`` existed --
``VBP0`` is the only one of the five with a boundary pin, which is why it
was the only one issue #376 could see from ``vco_block``'s own assembled
LVS. ``_pmos_row_escape()`` (used for every PMOS-row bottom *and* gate pad
instead of the general ``escape()``) hops onto Metal2 for exactly the
crossing -- Metal2 has no spacing relationship with Metal1 at all, the same
fact ``block.py``'s own top-level routing and ``ring.py``'s #371 fix both
already lean on -- then returns to Metal1 for the rest of the descent. See
``layout/evidence/vco-layout/PROOF-376-vbp0-fix.md`` -- including that
record's own disclosure that this fix, by resolving the ``VBP0``/``VDD_VCO``
short, exposes a distinct, separately-scoped ``NC``/``NOFF``/``NVI`` circuit-pin
artifact in the assembled ``vco_block`` LVS, filed as issue #378.

Standalone-DRC scope: like every other VCO sub-block, this one draws its
own dedicated guard ring (outer substrate ``p`` ring tied ``GND_VCO``, an
n-well tap band tied ``VDD_VCO``) so it is provable on its own.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from . import devices as dev
from . import primitives as prim
from ._escape_builder import EscapeBuilderMixin

TOP_CELL = "vco_vtoi_core"

VDD_NET = "VDD_VCO"
GND_NET = "GND_VCO"

# --- generator geometry (um) -- same values as mirror.py's own mesh block,
# for the same reasons (see that module's own constant docs). ---
SD_OVERHANG_UM = 1.5
DEVICE_GAP_UM = 3.4
FINGER_GAP_UM = 3.0  # between MSUM's own fingers
JOG_ESCAPE_UM = 1.1
ESCAPE_WIRE_W_UM = 0.44
TRACK_PITCH_UM = 0.8
CHANNEL_MARGIN_UM = 1.0
LINK_PITCH_UM = 1.0
LINK_MARGIN_UM = 3.0

TAP_GAP_UM = 0.6
TAP_BAND_WIDTH_UM = 0.6
RING_WIDTH_UM = 1.2
OUTER_MARGIN_LEFT_UM = 3.0
OUTER_MARGIN_RIGHT_UM = 3.0
OUTER_MARGIN_BELOW_UM = 2.5
OUTER_MARGIN_ABOVE_UM = 2.5

# Inter-device net order (excludes VDD_VCO/GND_VCO rails and MSU1's own
# GND_VCO-tied gate, which is routed separately -- see module docstring).
NET_ORDER = (
    "VCTRL",
    "NC",
    "NOFF",
    "NVI",
    "NA",
    "NMD",
    "NSU",
    "VFIX",
    "VBPC",
    "VBP0",
)

NMOS_ROW = tuple(f.name for f in dev.VTOI_NMOS_ROW)
PMOS_ROW = tuple(f.name for f in dev.VTOI_PMOS_ROW)


def _device_index() -> dict[str, dev.Fet]:
    return {f.name: f for f in dev.VTOI_ALL_FETS}


DEVICES = _device_index()


def device_height_um(l_um: float) -> float:
    return 2 * SD_OVERHANG_UM + l_um


def finger_footprint_w_um(fet: dev.Fet) -> float:
    """One finger's own drawn x-footprint, after MSU1's dog-bone widening.

    ``MSU1`` (``w=0.22 um``) is narrower than ``primitives.MIN_SD_CONTACT_
    WIDTH_UM`` (0.42 um) -- too narrow to drop a legal S/D contact into
    without ``primitives.mosfet()``'s ``min_sd_width_um`` dog-bone (see that
    parameter's own docstring). Every other device in this block is already
    wider than the floor, so this is a no-op for them.
    """
    return max(fet.finger_w_um, prim.MIN_SD_CONTACT_WIDTH_UM)


def item_width_um(fet: dev.Fet) -> float:
    """Pure-Python: the total x-footprint of ``fet`` (all fingers + gaps)."""
    n = fet.fingers
    fw = finger_footprint_w_um(fet)
    if n <= 1:
        return fw
    return n * fw + (n - 1) * FINGER_GAP_UM


# ---------------------------------------------------------------------------
# Placement plan -- pure Python (no KLayout import), mirroring mirror.py's
# own Plan/Item split so footprint_um() and the tests derive the block's
# extents from the same arithmetic build() draws from.
# ---------------------------------------------------------------------------


@dataclass
class Item:
    name: str
    x0: float
    width: float
    fet: dev.Fet


@dataclass
class Plan:
    pmos: list[Item] = field(default_factory=list)
    nmos: list[Item] = field(default_factory=list)
    net_rows: dict[str, set] = field(default_factory=dict)
    track_lo: dict[str, float] = field(default_factory=dict)
    track_hi: dict[str, float] = field(default_factory=dict)
    link_x: dict[str, float] = field(default_factory=dict)
    channel: tuple[float, float] = (0.0, 0.0)
    pmos_top: float = 0.0
    pmos_bottom: float = 0.0
    nwell: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0)
    tap_band: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0)
    tap_band_bottom: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0)
    outer: tuple[float, float, float, float] = (0.0, 0.0, 0.0, 0.0)
    _columns: list = field(default_factory=list)

    # -- mirror.py's BankPlan-shaped stand-in (see _escape_builder.py's
    # module docstring): this block has exactly one implicit bank, so
    # ``index``/``nmos_bottom`` are fixed rather than per-bank. ``pmos_top``
    # and ``track_y()`` already existed above for this module's own use. --
    index: int = 0
    nmos_bottom: float = 0.0

    def track_y(self, net: str, row: str) -> float:
        return self.track_lo[net] if row == "nfet" else self.track_hi[net]

    def reserve(self, net: str, x0: float, y0: float, x1: float, y1: float) -> None:
        s = dev.DRC_METAL1_MIN_SPACE_UM
        for other_net, ox0, oy0, ox1, oy1 in self._columns:
            if other_net == net:
                continue
            if x0 - s < ox1 and ox0 < x1 + s and y0 - s < oy1 and oy0 < y1 + s:
                raise ValueError(
                    f"Metal1 escape columns for {net!r} and {other_net!r} are closer than "
                    f"M1.2a's {s} um: ({x0:.3f},{y0:.3f})-({x1:.3f},{y1:.3f}) vs "
                    f"({ox0:.3f},{oy0:.3f})-({ox1:.3f},{oy1:.3f})"
                )
        self._columns.append((net, x0, y0, x1, y1))


def _row_items(names: tuple[str, ...]) -> list[Item]:
    items: list[Item] = []
    x = 0.0
    for name in names:
        fet = DEVICES[name]
        w = item_width_um(fet)
        items.append(Item(name=name, x0=x, width=w, fet=fet))
        x += w + DEVICE_GAP_UM
    return items


def _net_rows(pmos: list[Item], nmos: list[Item]) -> dict[str, set]:
    """Which transistor row(s) each mesh-routed net is escaped from.

    Excludes ``VDD_VCO``/``GND_VCO`` -- source/drain rail ties use
    ``rail_stub()`` directly, and the one rail-tied *gate* in this block
    (``MSU1``) is handled by its own bespoke wire in ``build()``, not the
    general mesh (see the module docstring).
    """
    rows: dict[str, set] = {}

    def add(net: str, row: str) -> None:
        if net in (VDD_NET, GND_NET):
            return
        rows.setdefault(net, set()).add(row)

    for items, row in ((pmos, "pfet"), (nmos, "nfet")):
        for it in items:
            f = it.fet
            add(f.gate_net, row)
            add(f.top_net, row)
            add(f.bottom_net, row)
    return rows


def plan() -> Plan:
    p = Plan()
    p.pmos = _row_items(PMOS_ROW)
    p.nmos = _row_items(NMOS_ROW)
    p.net_rows = _net_rows(p.pmos, p.nmos)

    missing = set(p.net_rows) - set(NET_ORDER)
    if missing:
        raise ValueError(f"nets with no track assignment: {sorted(missing)}")

    nmos_h = max(device_height_um(it.fet.l_um) for it in p.nmos)
    pmos_h = max(device_height_um(it.fet.l_um) for it in p.pmos)

    lo_nets = [n for n in NET_ORDER if "nfet" in p.net_rows.get(n, ())]
    hi_nets = [n for n in NET_ORDER if "pfet" in p.net_rows.get(n, ())]
    ch_y0 = nmos_h + CHANNEL_MARGIN_UM
    for i, net in enumerate(lo_nets):
        p.track_lo[net] = ch_y0 + TRACK_PITCH_UM / 2.0 + i * TRACK_PITCH_UM
    base_hi = ch_y0 + len(lo_nets) * TRACK_PITCH_UM
    for j, net in enumerate(hi_nets):
        p.track_hi[net] = base_hi + TRACK_PITCH_UM / 2.0 + j * TRACK_PITCH_UM
    ch_y1 = base_hi + len(hi_nets) * TRACK_PITCH_UM
    p.channel = (ch_y0, ch_y1)
    for net in NET_ORDER:
        if net not in p.track_lo:
            p.track_lo[net] = p.track_hi[net]
        elif net not in p.track_hi:
            p.track_hi[net] = p.track_lo[net]

    # --- both a top AND a bottom n-well tap band (unlike mirror.py's single
    # top band): MSU1's L=20 um channel makes it, by construction, the
    # tallest device in this row (pmos_h == its own device_height), so it
    # spans the row's *entire* height -- a single top-only band would leave
    # its own lower half more than DF.13_MV/DF.14_MV's 15 um bound from any
    # tap. Two bands bound the worst case at half of pmos_h plus one gap
    # instead of the full height -- see max_pmos_tap_distance_um(). ---
    p.pmos_bottom = ch_y1 + CHANNEL_MARGIN_UM + TAP_GAP_UM + TAP_BAND_WIDTH_UM + TAP_GAP_UM
    p.pmos_top = p.pmos_bottom + pmos_h

    pmos_x0 = p.pmos[0].x0
    pmos_x1 = p.pmos[-1].x0 + p.pmos[-1].width
    p.tap_band = (
        pmos_x0,
        p.pmos_top + TAP_GAP_UM,
        pmos_x1,
        p.pmos_top + TAP_GAP_UM + TAP_BAND_WIDTH_UM,
    )
    p.tap_band_bottom = (
        pmos_x0,
        p.pmos_bottom - TAP_GAP_UM - TAP_BAND_WIDTH_UM,
        pmos_x1,
        p.pmos_bottom - TAP_GAP_UM,
    )
    m = prim.NWELL_MARGIN_UM
    p.nwell = (pmos_x0 - m, p.tap_band_bottom[1] - m, pmos_x1 + m, p.tap_band[3] + m)

    rows_right = (
        max(pmos_x1, p.nmos[-1].x0 + p.nmos[-1].width)
        + JOG_ESCAPE_UM
        + ESCAPE_WIRE_W_UM / 2.0
    )
    link_nets = [n for n in NET_ORDER if p.net_rows.get(n, set()) == {"nfet", "pfet"}]
    for k, net in enumerate(link_nets):
        p.link_x[net] = rows_right + LINK_MARGIN_UM + k * LINK_PITCH_UM

    tab_dx = prim.POLY_ENDCAP_UM - prim.GATE_TAB_OVERLAP_UM + prim.GATE_TAB_W_UM + prim.METAL1_PAD_MARGIN_UM
    left_metal = -tab_dx
    right_metal = max([rows_right] + [x + ESCAPE_WIRE_W_UM / 2.0 for x in p.link_x.values()])
    # MSU1's own gate-tie wire (module docstring) runs from its own gate pad
    # out to the guard ring's right band, past every other item in the PMOS
    # row -- the outer ring's right edge itself, computed below, is that
    # wire's landing point, so no separate extent term is needed for it.
    gnd_pad_y0 = prim.CONTACT_ROW_MARGIN_UM - prim.METAL1_PAD_MARGIN_UM

    p.outer = (
        min(p.nwell[0], left_metal) - OUTER_MARGIN_LEFT_UM,
        gnd_pad_y0 - OUTER_MARGIN_BELOW_UM - RING_WIDTH_UM,
        max(p.nwell[2], right_metal) + OUTER_MARGIN_RIGHT_UM,
        p.nwell[3] + OUTER_MARGIN_ABOVE_UM,
    )
    return p


def footprint_um() -> tuple:
    return plan().outer


def max_pmos_tap_distance_um() -> float:
    """Worst-case pfet-to-nearest-n-well-tap distance (DF.13_MV/DF.14_MV).

    Two tap bands (top and bottom, see ``plan()``'s own note on why one band
    is not enough here) bound the worst case at half of the tallest device's
    own height plus one gap, not the full height.
    """
    p = plan()
    return (p.pmos_top - p.pmos_bottom) / 2.0 + TAP_GAP_UM


def max_nmos_tap_distance_um() -> float:
    """Worst-case nfet-to-nearest-substrate-tap (outer p-ring bottom band)."""
    p = plan()
    nmos_h = max(device_height_um(it.fet.l_um) for it in p.nmos)
    ring_top = p.outer[1] + RING_WIDTH_UM
    return nmos_h - ring_top


# ---------------------------------------------------------------------------
# Drawing
# ---------------------------------------------------------------------------


@dataclass
class VtoiCoreResult:
    canvas: prim.Canvas
    plan: Plan
    footprint: tuple = (0.0, 0.0, 0.0, 0.0)
    net_x: dict = field(default_factory=dict)


class _Builder(EscapeBuilderMixin):
    def __init__(self, canvas: prim.Canvas | None = None) -> None:
        self.plan = plan()
        self.canvas = prim.Canvas(TOP_CELL) if canvas is None else canvas
        self.net_x: dict[tuple[str, int, str], list[float]] = {}
        self.escape_wire_w_um = ESCAPE_WIRE_W_UM

    # -- escape()/jog_escape()/rail_stub()/_y_bottom() are inherited from
    # EscapeBuilderMixin -- identical construction to mirror.py's own (see
    # that module's docstring for the two-track-group rationale), factored
    # out in _escape_builder.py. This block passes ``self.plan`` itself as
    # the ``bank`` argument those methods take: it has exactly one implicit
    # bank, and ``Plan`` above carries the same index/pmos_top/nmos_bottom/
    # track_y() a one-bank stand-in would need. -----------------------------

    # -- devices -------------------------------------------------------------
    @staticmethod
    def _bus(pads: list[tuple]) -> tuple:
        x0 = min(p[0] for p in pads)
        x1 = max(p[2] for p in pads)
        return (x0, pads[0][1], x1, pads[0][3])

    def _pmos_row_escape(self, net: str, x: float, pad_edge_y: float) -> None:
        """Like ``escape()``, for a PMOS-row pad (bottom *or* gate) -- but
        hops onto Metal2 across ``plan.tap_band_bottom`` (issue #376).

        Every PMOS-row device here is *top*-aligned to ``plan.pmos_top``
        (``_y_bottom()``'s own pfet convention), so a device's own bottom
        and gate pads always sit *above* ``tap_band_bottom`` -- the
        ``VDD_VCO`` n-well tap band ``build()`` draws along the row's own
        bottom edge, spanning the row's full width (``plan.tap_band_bottom
        [0]`` to ``[2]`` == every PMOS item's own x-range). A plain
        ``escape()`` column descending from either pad straight down to the
        inter-row channel -- what every other mesh-routed net in this block
        uses -- would run its own Metal1 directly through the tap band's own
        drawn Metal1 (``primitives.tap_strip()``: comp + contact + a Metal1
        pad), merging whatever net escapes there into ``VDD_VCO``.
        Root-caused by direct ``klayout.db`` connectivity probing, not
        assumed: every one of this row's own bottom *and* gate escapes
        (``NA``, ``VBPC`` -- reached from three different devices' own gate
        and/or bottom pads -- ``VFIX``, ``VBP0``, ``NSU``) showed this
        identical merge before this method existed -- ``VBP0`` is the only
        one of them with a boundary pin, which is why it was the only one
        issue #376 could see from ``vco_block``'s own assembled LVS. See
        ``layout/evidence/vco-layout/PROOF-376-vbp0-fix.md``.

        Metal2 has no spacing relationship with Metal1 (the same fact
        ``block.py``'s own top-level routing and ``ring.py``'s #371 fix both
        already lean on), so this runs Metal1 from the pad down to just
        above the tap band's own drawn edge, hops onto Metal2 for exactly
        the crossing, then returns to Metal1 (via the ordinary ``escape()``)
        for the rest of the descent to the net's own channel track --
        unconditionally, for *every* PMOS-row escape regardless of whether
        its own x happens to fall inside the tap band's drawn extent, the
        same "no obstruction inventory needed" shape ``ring.py``'s own
        wraparound-riser fix used for an analogous same-layer crossing.
        """
        tb = self.plan.tap_band_bottom
        # tap_strip() itself grows the tap band's own drawn Metal1 pad
        # METAL1_PAD_MARGIN_UM past the comp box ``tap_band_bottom`` gives,
        # and via1_stack()'s own landing pad (half-width VIA1_SIZE_UM/2 +
        # VIA1_METAL_ENCLOSE_UM) is what actually has to clear that edge by
        # DRC_METAL1_MIN_SPACE_UM (M1.2a) -- not the hop point itself.
        via_half_pad = prim.VIA1_SIZE_UM / 2.0 + prim.VIA1_METAL_ENCLOSE_UM
        clear = prim.METAL1_PAD_MARGIN_UM + dev.DRC_METAL1_MIN_SPACE_UM + via_half_pad
        hop_hi = tb[3] + clear  # just above the tap band's own drawn Metal1
        hop_lo = tb[1] - clear  # just below it
        if not pad_edge_y > hop_hi:
            raise ValueError(
                f"{net!r}'s own pad ({pad_edge_y}) does not clear the tap band's "
                f"own hop zone (>{hop_hi}) -- _pmos_row_escape()'s own "
                "top-aligned-row assumption no longer holds"
            )
        half = self.escape_wire_w_um / 2.0
        prim.v_wire(self.canvas, x, pad_edge_y, hop_hi, width=self.escape_wire_w_um)
        prim.via1_stack(self.canvas, x, hop_hi)
        self.canvas.rect("metal2", x - half, hop_lo, x + half, hop_hi)
        prim.via1_stack(self.canvas, x, hop_lo)
        self.plan.reserve(net, x - half, hop_hi, x + half, pad_edge_y)
        # The rest of the descent (hop_lo -> the net's own channel track) is
        # an ordinary Metal1 escape() -- same reserve()/net_x bookkeeping
        # every other mesh-routed net gets.
        self.escape(net, x, hop_lo, "pfet", self.plan)

    def draw_fet(self, item: Item, row: str) -> None:
        fet = item.fet
        y_bottom = self._y_bottom(row, device_height_um(fet.l_um), self.plan)
        n = fet.fingers
        fw = fet.finger_w_um

        footprint_w = finger_footprint_w_um(fet)
        finger_ports = []
        x = item.x0
        for _ in range(n):
            finger_ports.append(
                prim.mosfet(
                    self.canvas,
                    fet,
                    x,
                    y_bottom,
                    w_um=fw,
                    sd_overhang=SD_OVERHANG_UM,
                    min_sd_width_um=prim.MIN_SD_CONTACT_WIDTH_UM,
                )
            )
            x += footprint_w + FINGER_GAP_UM

        if n == 1:
            p0 = finger_ports[0]
            bottom_pad, top_pad, gate_pad = p0.bottom_pad, p0.top_pad, p0.gate_pad
            gate_tab_x_center = p0.gate_tab_x_center
        else:
            bottom_pad = self._bus([p.bottom_pad for p in finger_ports])
            top_pad = self._bus([p.top_pad for p in finger_ports])
            gate_pad = self._bus([p.gate_pad for p in finger_ports])
            self.canvas.rect("metal1", *bottom_pad)
            self.canvas.rect("metal1", *top_pad)
            self.canvas.rect("metal1", *gate_pad)
            gate_tab_x_center = (gate_pad[0] + gate_pad[2]) / 2.0

        x_pad_c = (bottom_pad[0] + bottom_pad[2]) / 2.0
        x_jog = item.x0 + item.width + JOG_ESCAPE_UM

        if row == "pfet":
            if fet.top_net == VDD_NET:
                self.rail_stub(VDD_NET, x_pad_c, top_pad[3], self.plan.tap_band[1])
            else:
                self.jog_escape(fet.top_net, top_pad, x_jog, row, self.plan)
            self._pmos_row_escape(fet.bottom_net, x_pad_c, bottom_pad[1])
            if fet.gate_net == GND_NET:
                # MSU1: tie its gate directly to the guard ring's right band
                # (module docstring) -- drawn once, after every item is
                # placed, in build() (needs self.plan.outer[2]).
                self._msu1_gate_pad = gate_pad
            else:
                self._pmos_row_escape(fet.gate_net, gate_tab_x_center, gate_pad[1])
        else:
            if fet.bottom_net == GND_NET:
                ring_top = self.plan.outer[1] + RING_WIDTH_UM + prim.METAL1_PAD_MARGIN_UM
                self.rail_stub(GND_NET, x_pad_c, bottom_pad[1], ring_top)
            else:
                self.jog_escape(fet.bottom_net, bottom_pad, x_jog, row, self.plan)
            self.escape(fet.top_net, x_pad_c, top_pad[3], row, self.plan)
            self.escape(fet.gate_net, gate_tab_x_center, gate_pad[3], row, self.plan)

    # -- assembly ------------------------------------------------------------
    def build(self) -> VtoiCoreResult:
        p = self.plan
        self._msu1_gate_pad: tuple | None = None
        for item in p.pmos:
            self.draw_fet(item, "pfet")
        for item in p.nmos:
            self.draw_fet(item, "nfet")

        pad = ESCAPE_WIRE_W_UM / 2.0
        track_x1: dict[str, float] = {}
        for net in NET_ORDER:
            for row in ("nfet", "pfet"):
                xs = self.net_x.get((net, p.index, row))
                if not xs:
                    continue
                x_link = p.link_x.get(net)
                x1 = max(xs + ([x_link] if x_link is not None else []))
                prim.m2_wire(self.canvas, min(xs) - pad, x1 + pad, p.track_y(net, row))
                track_x1[net] = max(track_x1.get(net, x1), x1)

        for net, x in p.link_x.items():
            y0, y1 = p.track_lo[net], p.track_hi[net]
            self.plan.reserve(net, x - pad, y0, x + pad, y1)
            prim.v_wire(self.canvas, x, y0, y1, width=ESCAPE_WIRE_W_UM)
            prim.via1_stack(self.canvas, x, y0)
            prim.via1_stack(self.canvas, x, y1)

        # --- MSU1's gate: one horizontal Metal1 run at the gate pad's own
        # height, straight into the guard ring's right band (see module
        # docstring's "THE ONE DEVICE THAT IS NOT MESH-ROUTED" section). ---
        if self._msu1_gate_pad is not None:
            gp = self._msu1_gate_pad
            y_c = (gp[1] + gp[3]) / 2.0
            width = gp[3] - gp[1]
            ring_inner_x = p.outer[2] - RING_WIDTH_UM
            self.plan.reserve("MSU1_GATE_GND_TIE", gp[0], gp[1], ring_inner_x, gp[3])
            prim.h_wire(self.canvas, gp[0], ring_inner_x + 0.5, y_c, width=width)

        # --- block boundary pins ---
        def _leftmost(net: str) -> tuple[float, float]:
            for row in ("nfet", "pfet"):
                xs = self.net_x.get((net, p.index, row))
                if xs:
                    return (min(xs), p.track_y(net, row))
            raise KeyError(net)

        single_row_pins = (dev.VTOI_IN_NET,) + dev.VTOI_RESISTOR_NETS
        for net in single_row_pins:
            x, y = _leftmost(net)
            self.canvas.pin(net, x - pad - 0.6, y - pad, x - pad, y + pad, layer="metal2_label")
            prim.m2_wire(self.canvas, x - pad - 0.6, x, y)

        y = p.track_hi[dev.VTOI_OUT_NET]
        x = track_x1[dev.VTOI_OUT_NET] + pad
        self.canvas.pin(dev.VTOI_OUT_NET, x, y - pad, x + 0.6, y + pad, layer="metal2_label")
        prim.m2_wire(self.canvas, x - pad, x + 0.6, y)

        # --- n-well, its VDD_VCO tap bands (top AND bottom -- see plan()'s
        # own note on why MSU1's L=20 um channel needs both), and the outer
        # GND_VCO guard ring. Both bands make ohmic contact to the same
        # continuous n-well body, so they are the same electrical net
        # without any extra Metal1 jumper between them. ---
        self.canvas.rect("nwell", *p.nwell)
        prim.tap_strip(self.canvas, "n", *p.tap_band, VDD_NET)
        prim.tap_strip(self.canvas, "n", *p.tap_band_bottom, VDD_NET)
        prim.guard_ring(self.canvas, "p", *p.outer, RING_WIDTH_UM, GND_NET)

        return VtoiCoreResult(canvas=self.canvas, plan=p, footprint=p.outer, net_x=self.net_x)


def build(outdir: Path | None = None, canvas: prim.Canvas | None = None) -> VtoiCoreResult:
    """``canvas`` draws into a caller-supplied canvas -- see ``ring.build()``."""
    result = _Builder(canvas).build()
    if outdir is not None:
        outdir = Path(outdir)
        outdir.mkdir(parents=True, exist_ok=True)
        result.canvas.write_gds(outdir / f"{TOP_CELL}.gds")
    return result


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--outdir",
        default=str(Path(__file__).resolve().parents[2] / "evidence" / "vco-layout" / "work"),
    )
    args = parser.parse_args()
    result = build(Path(args.outdir))
    x0, y0, x1, y1 = result.footprint
    print(f"wrote {args.outdir}/{TOP_CELL}.gds")
    print(f"footprint: {x1 - x0:.3f} x {y1 - y0:.3f} um  ({(x1 - x0) * (y1 - y0):.1f} um^2)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
